// Tableau d'objet de données en attendant de pouvoir faire appel à une API
// const gameDesc = [
//     { name: 'Tyrants of the underdark', type: 'Deck Building / Placement ouvriers', niveau: 'Avancé', age: '14+', langue: 'EN', cover: 'https://cf.geekdo-images.com/F58jczp5xk9CYFimrytXaw__imagepagezoom/img/w2wr5vUusTlCzeL-9jA3bEX_pBM=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic2801874.jpg' },
//     { name: 'Super Fantasy Brawl', type: 'Affrontements', niveau: 'Avancé', age: '10+', langue: 'FR', cover: 'https://cf.geekdo-images.com/yT5dXJzCpgvBBmXr_zQDSQ__imagepagezoom/img/zouJ5346Ek-LPTHZSE-O5PZblUg=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic4808077.jpg' },
//     { name: 'Shasn', type: 'Stratégie', niveau: 'Avancé', age: '16+', langue: 'EN', cover: 'https://cf.geekdo-images.com/REV41XH_xrquh9Unl_M2DA__imagepagezoom/img/90i47VKvslS-GkNuqzYDuXnW2FU=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic4745701.png' },
//     { name: 'A Game of Thrones', type: 'Stratégie', niveau: 'Expert', age: '14+', langue: 'FR', cover: 'https://cf.geekdo-images.com/M_7UvwZvuxBVjxdadsa5AA__imagepagezoom/img/ZPrM6snVy0ywNlmQeP7208In9pU=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic1077906.jpg' },
//     { name: 'Vampire la Masquarade : Vendetta', type: 'Stratégie', niveau: 'Avancé', age: '12+', langue: 'FR', cover: 'https://cf.geekdo-images.com/V3Ff1dIMh6QrU2IeZabr_g__imagepagezoom/img/TRC2ujszD9Dsr_xs8evokk6MsdI=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic4854194.png' },
//     { name: 'Shamans', type: 'Jeu de plis', niveau: 'Intermédiaire', age: '10+', langue: 'FR', cover: 'https://cf.geekdo-images.com/BNmYPPip0PZBPx9qJCEUxA__imagepagezoom/img/-MbZ9P_jhVg_ee0gQmyUEtvVlgw=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic6021323.jpg' },
//     { name: 'Shamans', type: 'Jeu de plis', niveau: 'Intermédiaire', age: '10+', langue: 'FR', cover: 'https://cf.geekdo-images.com/BNmYPPip0PZBPx9qJCEUxA__imagepagezoom/img/-MbZ9P_jhVg_ee0gQmyUEtvVlgw=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic6021323.jpg' },
//     { name: 'Shamans', type: 'Jeu de plis', niveau: 'Intermédiaire', age: '10+', langue: 'FR', cover: 'https://cf.geekdo-images.com/BNmYPPip0PZBPx9qJCEUxA__imagepagezoom/img/-MbZ9P_jhVg_ee0gQmyUEtvVlgw=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic6021323.jpg' },
//     { name: 'Shamans', type: 'Jeu de plis', niveau: 'Intermédiaire', age: '10+', langue: 'FR', cover: 'https://cf.geekdo-images.com/BNmYPPip0PZBPx9qJCEUxA__imagepagezoom/img/-MbZ9P_jhVg_ee0gQmyUEtvVlgw=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic6021323.jpg' },
//     { name: 'Shamans', type: 'Jeu de plis', niveau: 'Intermédiaire', age: '10+', langue: 'FR', cover: 'https://cf.geekdo-images.com/BNmYPPip0PZBPx9qJCEUxA__imagepagezoom/img/-MbZ9P_jhVg_ee0gQmyUEtvVlgw=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic6021323.jpg' },
//     { name: 'Shamans', type: 'Jeu de plis', niveau: 'Intermédiaire', age: '10+', langue: 'FR', cover: 'https://cf.geekdo-images.com/BNmYPPip0PZBPx9qJCEUxA__imagepagezoom/img/-MbZ9P_jhVg_ee0gQmyUEtvVlgw=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic6021323.jpg' },
//     { name: 'Shamans', type: 'Jeu de plis', niveau: 'Intermédiaire', age: '10+', langue: 'FR', cover: 'https://cf.geekdo-images.com/BNmYPPip0PZBPx9qJCEUxA__imagepagezoom/img/-MbZ9P_jhVg_ee0gQmyUEtvVlgw=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic6021323.jpg' },
//     { name: 'Shamans', type: 'Jeu de plis', niveau: 'Intermédiaire', age: '10+', langue: 'FR', cover: 'https://cf.geekdo-images.com/BNmYPPip0PZBPx9qJCEUxA__imagepagezoom/img/-MbZ9P_jhVg_ee0gQmyUEtvVlgw=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic6021323.jpg' },

// ]

const games = [
    {
        "ID": 3809,
        "Titre": "6 qui prend !",
        "Sous-titre": "",
        "Édition": 2012,
        "Type": "basegame",
        "EAN": 3421272101337,
        "Prix indicatif": 13,
        "Joueur(s)": "2 — 10",
        "Durée": "30 — 60",
        "Age(s)": "10+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "6 qui prend",
        "Catégorie(s)": "Jeu de Cartes",
        "Thème(s)": "Abstrait,Animaux,Vache",
        "Mécanisme(s)": "Bluff,Choix simultanés,Guessing",
        "Éditeur(s)": "Amigo Spiele,Gigamic",
        "Auteur(s)": "Wolfgang Kramer",
        "Illustrateur(s)": "Franz Vohwinkel",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 1005,
        "Titre": "7 Wonders Duel",
        "Sous-titre": "",
        "Édition": 2015,
        "Type": "basegame",
        "EAN": "5425016923801,5425016924235",
        "Prix indicatif": 25,
        "Joueur(s)": "Duo",
        "Durée": 30,
        "Age(s)": "10+",
        "Langues": "français",
        "Univers": "7 Wonders",
        "Gamme(s)": "7 Wonders Duel",
        "Catégorie(s)": "Jeu de Cartes,Jeu de plateau",
        "Thème(s)": "Antiquité,Civilisation",
        "Mécanisme(s)": "Affrontement Direct,Blocage,Construction,Course,Draft,Duo,Gestion de ressources,Majorité,Prise de risque",
        "Éditeur(s)": "Repos Production",
        "Auteur(s)": "Antoine Bauza,Bruno Cathala",
        "Illustrateur(s)": "Miguel Coimbra",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 40856,
        "Titre": "7 Wonders Duel - Agora",
        "Sous-titre": "",
        "Édition": 2020,
        "Type": "extension",
        "EAN": 5425016924310,
        "Prix indicatif": 20,
        "Joueur(s)": "Duo",
        "Durée": 30,
        "Age(s)": "10+",
        "Langues": "français",
        "Univers": "7 Wonders",
        "Gamme(s)": "7 Wonders Duel",
        "Catégorie(s)": "Jeu de Cartes,Jeu de plateau",
        "Thème(s)": "Antiquité,Civilisation,Politique",
        "Mécanisme(s)": "Affrontement Direct,Blocage,Construction,Course,Draft,Duo,Gestion de ressources,Majorité,Prise de risque",
        "Éditeur(s)": "Repos Production",
        "Auteur(s)": "Antoine Bauza,Bruno Cathala",
        "Illustrateur(s)": "Miguel Coimbra",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 1616,
        "Titre": "Abyss",
        "Sous-titre": "",
        "Édition": 2014,
        "Type": "basegame",
        "EAN": 3770000010053,
        "Prix indicatif": 40,
        "Joueur(s)": "2 — 4",
        "Durée": 45,
        "Age(s)": "14+",
        "Langues": "français",
        "Univers": "Abyss",
        "Gamme(s)": "Abyss",
        "Catégorie(s)": "Jeu de Cartes,Jeu de plateau",
        "Thème(s)": "Fantastique,Maritime,Mythologie,Océan,Science-fiction",
        "Mécanisme(s)": "Collection,Combinaison,Enchères,Gestion de main,Pioche,Pouvoir,Stop ou encore",
        "Éditeur(s)": "Bombyx",
        "Auteur(s)": "Bruno Cathala,Charles Chevallier",
        "Illustrateur(s)": "Xavier Collette",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 23357,
        "Titre": "Aeon's End",
        "Sous-titre": "",
        "Édition": 2018,
        "Type": "basegame",
        "EAN": 3760146644274,
        "Prix indicatif": 45,
        "Joueur(s)": "1 — 4",
        "Durée": "60 — 120",
        "Age(s)": "14+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Aeon's End",
        "Catégorie(s)": "Jeu de Cartes",
        "Thème(s)": "Médiéval Fantastique,Monstres",
        "Mécanisme(s)": "Coopération,Deck building,Gestion de main,Pouvoir",
        "Éditeur(s)": "Matagot",
        "Auteur(s)": "Kevin Riley",
        "Illustrateur(s)": "Gong Studios,Scott Hartman,Stephanie Gustafsson",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 57209,
        "Titre": "Alice is Missing",
        "Sous-titre": "",
        "Édition": 2022,
        "Type": "basegame",
        "EAN": 9791094150504,
        "Prix indicatif": 18,
        "Joueur(s)": "3 — 5",
        "Durée": "120+",
        "Age(s)": "16+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Alice is Missing",
        "Catégorie(s)": "Jeu De Rôle",
        "Thème(s)": "Enfant,Enquêtes & Mystères",
        "Mécanisme(s)": "Communication Restreinte,Coopération,Narration,Rôle,Scénario",
        "Éditeur(s)": "Origames",
        "Auteur(s)": "Spenser Starke",
        "Illustrateur(s)": "Julianne Griepp",
        "Date d'acquisition": "2024-05-29",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 4947,
        "Titre": "Bang!",
        "Sous-titre": "",
        "Édition": 2011,
        "Type": "basegame",
        "EAN": 3558380005605,
        "Prix indicatif": 20,
        "Joueur(s)": "4 — 7",
        "Durée": "20 — 40",
        "Age(s)": "8+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Bang!",
        "Catégorie(s)": "Jeu de Cartes",
        "Thème(s)": "Far West",
        "Mécanisme(s)": "Affrontement Direct,Combinaison,Équipe,Gestion de main,Rôle secret",
        "Éditeur(s)": "Dv Giochi",
        "Auteur(s)": "Emiliano Sciarra",
        "Illustrateur(s)": "Alex Pierangelini",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 5169,
        "Titre": "Boggle",
        "Sous-titre": "",
        "Édition": 1974,
        "Type": "basegame",
        "EAN": "",
        "Prix indicatif": 0,
        "Joueur(s)": "1 — 8",
        "Durée": 30,
        "Age(s)": "8+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Boggle",
        "Catégorie(s)": "Jeu de lettres",
        "Thème(s)": "Abstrait,Lettres",
        "Mécanisme(s)": "Logique",
        "Éditeur(s)": "Capiépa",
        "Auteur(s)": "Alan Turoff",
        "Illustrateur(s)": "",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 16613,
        "Titre": "Bohnanza",
        "Sous-titre": "",
        "Édition": 2009,
        "Type": "basegame",
        "EAN": 3421272104017,
        "Prix indicatif": 10,
        "Joueur(s)": "2 — 5",
        "Durée": 60,
        "Age(s)": "12+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Bohnanza",
        "Catégorie(s)": "Jeu de Cartes",
        "Thème(s)": "Commerce,Fruits & légumes",
        "Mécanisme(s)": "Collection,Commerce,Échange & Troc,Gestion de main",
        "Éditeur(s)": "Gigamic",
        "Auteur(s)": "Uwe Rosenberg",
        "Illustrateur(s)": "Björn Pertoft",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 35740,
        "Titre": "Carcassonne",
        "Sous-titre": "",
        "Édition": 2016,
        "Type": "basegame",
        "EAN": 8435407619968,
        "Prix indicatif": "24,95",
        "Joueur(s)": "2 — 5",
        "Durée": "30 — 60",
        "Age(s)": "8+",
        "Langues": "français",
        "Univers": "Carcassonne",
        "Gamme(s)": "Carcassonne",
        "Catégorie(s)": "Jeu de tuiles",
        "Thème(s)": "Médiéval,Ville",
        "Mécanisme(s)": "Blocage,Connexion,Majorité,Placement,Pose de tuiles",
        "Éditeur(s)": "Hans Im Glück,Z-Man Games",
        "Auteur(s)": "Klaus-Jürgen Wrede",
        "Illustrateur(s)": "Anne Pätzke,Chris Quilliams",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 19557,
        "Titre": "Citadelles",
        "Sous-titre": "",
        "Édition": 2016,
        "Type": "basegame",
        "EAN": "3558380038924,8433407639126",
        "Prix indicatif": 15,
        "Joueur(s)": "2 — 7",
        "Durée": "30 — 60",
        "Age(s)": "10+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Citadelles",
        "Catégorie(s)": "Jeu de Cartes",
        "Thème(s)": "Médiéval Fantastique",
        "Mécanisme(s)": "Bluff,Choix multiples,Choix simultanés,Construction,Draft,Gestion de main,Pouvoir",
        "Éditeur(s)": "Edge Entertainment",
        "Auteur(s)": "Bruno Faidutti",
        "Illustrateur(s)": "Didier Graffet,Florence Magnin,Jean-Louis Mourier,Julien Delval",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 3648,
        "Titre": "City of Horror",
        "Sous-titre": "",
        "Édition": 2012,
        "Type": "basegame",
        "EAN": "",
        "Prix indicatif": 50,
        "Joueur(s)": "3 — 6",
        "Durée": 60,
        "Age(s)": "10+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "City of Horror",
        "Catégorie(s)": "Jeu de plateau",
        "Thème(s)": "Horreur,Survie,Zombies",
        "Mécanisme(s)": "Dans Ta Face,Diplomatie,Négociation,Trahison",
        "Éditeur(s)": "Repos Production",
        "Auteur(s)": "Nicolas Normandon",
        "Illustrateur(s)": "Miguel Coimbra",
        "Date d'acquisition": "2022-01-22",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 23635,
        "Titre": "Coimbra",
        "Sous-titre": "",
        "Édition": 2018,
        "Type": "basegame",
        "EAN": 4061897521104,
        "Prix indicatif": 44,
        "Joueur(s)": "2 — 4",
        "Durée": "60 — 90",
        "Age(s)": "14+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Coimbra",
        "Catégorie(s)": "Jeu de dés",
        "Thème(s)": "Portugal,Renaissance,Ville",
        "Mécanisme(s)": "Collection,Draft,Jet De Dés",
        "Éditeur(s)": "Eggertspiele",
        "Auteur(s)": "Flaminia Brasini,Virginio Gigli",
        "Illustrateur(s)": "Chris Quilliams",
        "Date d'acquisition": "2022-01-22",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 73844,
        "Titre": "Courtisans",
        "Sous-titre": "",
        "Édition": 2024,
        "Type": "basegame",
        "EAN": 3760273010423,
        "Prix indicatif": "17,9",
        "Joueur(s)": "2 — 5",
        "Durée": "20 — 30",
        "Age(s)": "8+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "",
        "Catégorie(s)": "Jeu de Cartes",
        "Thème(s)": "Médiéval,Royauté",
        "Mécanisme(s)": "Chance & Hasard,Choix multiples,Collection,Dans Ta Face,Majorité,Placement de cartes,Pouvoir",
        "Éditeur(s)": "Catch Up Games",
        "Auteur(s)": "Anthony Perone,Romaric Galonnier",
        "Illustrateur(s)": "Noëmie Chevalier",
        "Date d'acquisition": "2024-05-29",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 7225,
        "Titre": "Cyclades",
        "Sous-titre": "",
        "Édition": 2009,
        "Type": "basegame",
        "EAN": 3760146642010,
        "Prix indicatif": 49,
        "Joueur(s)": "2 — 5",
        "Durée": 90,
        "Age(s)": "10+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Cyclades",
        "Catégorie(s)": "Jeu de plateau",
        "Thème(s)": "Antiquité,Grèce,Guerre,Les îles,Monstres,Mythologie",
        "Mécanisme(s)": "Conquête,Contrôle de zone,Enchères,Gestion,Jet De Dés,Majorité,Plateau modulaire",
        "Éditeur(s)": "Matagot",
        "Auteur(s)": "Bruno Cathala,Ludovic Maublanc",
        "Illustrateur(s)": "Miguel Coimbra",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 28270,
        "Titre": "Dany",
        "Sous-titre": "",
        "Édition": 2019,
        "Type": "basegame",
        "EAN": 3760290560000,
        "Prix indicatif": "15,9",
        "Joueur(s)": "3 — 8",
        "Durée": 30,
        "Age(s)": "16+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Dany",
        "Catégorie(s)": "Jeu de Cartes",
        "Thème(s)": "Abstrait,Onirique",
        "Mécanisme(s)": "Bluff,Déduction,Rôle",
        "Éditeur(s)": "Grrre Games",
        "Auteur(s)": "Phil Vizcarro",
        "Illustrateur(s)": "Bengal",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 1385,
        "Titre": "Dead of Winter",
        "Sous-titre": "À la croisée des chemins",
        "Édition": 2014,
        "Type": "basegame",
        "EAN": "0688623420001,8435407621831",
        "Prix indicatif": 59,
        "Joueur(s)": "2 — 5",
        "Durée": "60 — 120",
        "Age(s)": "13+",
        "Langues": "français,anglais",
        "Univers": "",
        "Gamme(s)": "Dead Of Winter",
        "Catégorie(s)": "Jeu de plateau",
        "Thème(s)": "Horreur,Post-apocalyptique,Survie,Zombies",
        "Mécanisme(s)": "Bluff,Coopération,Diplomatie,Narration,Objectif secret,Points d'action,Rôle secret,Semi-coopération,Trahison",
        "Éditeur(s)": "Filosofia,Plaid Hat Games",
        "Auteur(s)": "Isaac Vega,Jonathan Gilmour",
        "Illustrateur(s)": "Fernanda Suarez",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 28994,
        "Titre": "Dig your way out",
        "Sous-titre": "",
        "Édition": 2019,
        "Type": "basegame",
        "EAN": 3770003625612,
        "Prix indicatif": 35,
        "Joueur(s)": "2 — 6",
        "Durée": "40 — 45",
        "Age(s)": "16+",
        "Langues": "français,anglais",
        "Univers": "",
        "Gamme(s)": "Dig your way out",
        "Catégorie(s)": "Jeu de plateau",
        "Thème(s)": "Évasion,Gangs,Mafia,Prison",
        "Mécanisme(s)": "Déduction,Jet De Dés,Points d'action",
        "Éditeur(s)": "Borderline",
        "Auteur(s)": "David Simide",
        "Illustrateur(s)": "Mihajlo Dimitrievski",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 259,
        "Titre": "Docteur Pilule",
        "Sous-titre": "",
        "Édition": 2016,
        "Type": "basegame",
        "EAN": 3760032260724,
        "Prix indicatif": 19,
        "Joueur(s)": "4 — 10",
        "Durée": "15 — 30",
        "Age(s)": "10+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Docteur Pilule",
        "Catégorie(s)": "Jeu d'Ambiance,Jeu de plateau",
        "Thème(s)": "Sciences",
        "Mécanisme(s)": "Affrontement Direct,Déduction,Équipe,Gestion de main",
        "Éditeur(s)": "Fantastic Lombric",
        "Auteur(s)": "Guillaume Brunier,Jacques Exetier,Jean-Philippe Caro",
        "Illustrateur(s)": "Guillaume Brunier,Jacques Exertier,Jean-Phillipe Caro",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 37573,
        "Titre": "Dual Powers",
        "Sous-titre": "Revolution 1917",
        "Édition": 2020,
        "Type": "basegame",
        "EAN": 3663411310631,
        "Prix indicatif": 30,
        "Joueur(s)": "1 — 2",
        "Durée": "30 — 60",
        "Age(s)": "13+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Dual Powers",
        "Catégorie(s)": "Jeu de plateau",
        "Thème(s)": "Guerre,Historique,Politique,Russie",
        "Mécanisme(s)": "Conquête,Déduction,Gestion de main",
        "Éditeur(s)": "Don't Panic Games",
        "Auteur(s)": "Brett Myers",
        "Illustrateur(s)": "Kwanchai Moriya,Luis Francisco",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    },
    {
        "ID": 21314,
        "Titre": "Exit - La Cabane Abandonnée",
        "Sous-titre": "",
        "Édition": 2017,
        "Type": "basegame",
        "EAN": 3760175514395,
        "Prix indicatif": "12,5",
        "Joueur(s)": "1 — 6",
        "Durée": "60 — 120",
        "Age(s)": "12+",
        "Langues": "français",
        "Univers": "",
        "Gamme(s)": "Exit",
        "Catégorie(s)": "Escape Game",
        "Thème(s)": "Enquêtes & Mystères,Nature",
        "Mécanisme(s)": "Altération de Matériel,Coopération,Déduction,Défis,Énigme,Logique,Observation,Réflexion",
        "Éditeur(s)": "Iello,Kosmos",
        "Auteur(s)": "Inka Brand,Markus Brand",
        "Illustrateur(s)": "Franz Vohwinkel",
        "Date d'acquisition": "2022-01-17",
        "Propriétaire": "",
        "Cadeaux": "",
        "Emplacement": "",
        "Prix d'achat": "",
        "État": "",
        "Privé": "non",
        "Commentaire": "",
        "Référence": "",
        "Référent": "",
        "Dernière partie": ""
    }
]

// Variable pour accéder à toutes les balides dans le code HTML (page 'Ma Collection')
const gamesImages = document.querySelectorAll('.wrapper img');
const gamesTitres = document.querySelectorAll('.name');
const gamesTypes = document.querySelectorAll('.type');
const gamesLevel = document.querySelectorAll('.niveau');
const gamesAge = document.querySelectorAll('.age');
const gamesLang = document.querySelectorAll('.langue');

// Boucle pour récupérer toutes les informations dans le tableau d'objet et les envoyer aux bons endroits
for (let i = 0; i < games.length; i++) {
    if (games[i].cover != '') {
        gamesImages[i].src = gameDesc[i].cover
    } else {
        gamesImages[i].src = '/img/no-photo.jpg'

    }

    if (gameDesc[i].name != '') {
        gamesTitres[i].innerText = gameDesc[i].Titre
    }

    if (gameDesc[i].type != '') {
        gamesTypes[i].innerText = gameDesc[i].type
    }

    if (gameDesc[i].niveau != '') {
        gamesLevel[i].innerText = gameDesc[i].niveau
    }

    if (gameDesc[i].age != '') {
        gamesAge[i].innerText = gameDesc[i].age
    }

    if (gameDesc[i].langue != '') {
        gamesLang[i].innerText = gameDesc[i].langue
    }


}



