// --- CONTENU API --- 
const games = [
    {
      "ID": 3809,
      "Titre": "6 qui prend !",
      "Sous-titre": "",
      "Edition": 2012,
      "Type": "basegame",
      "EAN": "3421272101337",
      "Prix": "13",
      "Joueurs": "2 — 10",
      "Duree": "30 — 60",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "6 qui prend",
      "Categories": "Jeu de Cartes",
      "Themes": "Abstrait,Animaux,Vache",
      "Mecanismes": "Bluff,Choix simultanés,Guessing",
      "Editeurs": "Amigo Spiele,Gigamic",
      "Auteurs": "Wolfgang Kramer",
      "Illustrateurs": "Franz Vohwinkel",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-Date-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1680439738/300/ad/3809.png"
    },
    {
      "ID": 1005,
      "Titre": "7 Wonders Duel",
      "Sous-titre": "",
      "Edition": 2015,
      "Type": "basegame",
      "EAN": "5425016923801,5425016924235",
      "Prix": "25",
      "Joueurs": "Duo",
      "Duree": "30",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "7 Wonders",
      "Gammes": "7 Wonders Duel",
      "Categories": "Jeu de Cartes,Jeu de plateau",
      "Themes": "Antiquité,Civilisation",
      "Mecanismes": "Affrontement Direct,Blocage,Construction,Course,Draft,Duo,Gestion de ressources,Majorité,Prise de risque",
      "Editeurs": "Repos Production",
      "Auteurs": "Antoine Bauza,Bruno Cathala",
      "Illustrateurs": "Miguel Coimbra",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1721206192/jpg/ab/1005.jpg"

    },
    {
      "ID": 40856,
      "Titre": "7 Wonders Duel - Agora",
      "Sous-titre": "",
      "Edition": 2020,
      "Type": "extension",
      "EAN": "5425016924310",
      "Prix": "20",
      "Joueurs": "Duo",
      "Duree": "30",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "7 Wonders",
      "Gammes": "7 Wonders Duel",
      "Categories": "Jeu de Cartes,Jeu de plateau",
      "Themes": "Antiquité,Civilisation,Politique",
      "Mecanismes": "Affrontement Direct,Blocage,Construction,Course,Draft,Duo,Gestion de ressources,Majorité,Prise de risque",
      "Editeurs": "Repos Production",
      "Auteurs": "Antoine Bauza,Bruno Cathala",
      "Illustrateurs": "Miguel Coimbra",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1706716389/jpg/bo/40856.jpg"
    },
    {
      "ID": 1616,
      "Titre": "Abyss",
      "Sous-titre": "",
      "Edition": 2014,
      "Type": "basegame",
      "EAN": "3770000010053",
      "Prix": "40",
      "Joueurs": "2 — 4",
      "Duree": "45",
      "Ages": "14+",
      "Langues": "français",
      "Univers": "Abyss",
      "Gammes": "Abyss",
      "Categories": "Jeu de Cartes,Jeu de plateau",
      "Themes": "Fantastique,Maritime,Mythologie,Océan,Science-fiction",
      "Mecanismes": "Collection,Combinaison,Enchères,Gestion de main,Pioche,Pouvoir,Stop ou encore",
      "Editeurs": "Bombyx",
      "Auteurs": "Bruno Cathala,Charles Chevallier",
      "Illustrateurs": "Xavier Collette",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1659803682/300/ab/1616.png"
    },
    {
      "ID": 23357,
      "Titre": "Aeon's End",
      "Sous-titre": "",
      "Edition": 2018,
      "Type": "basegame",
      "EAN": "3760146644274",
      "Prix": "45",
      "Joueurs": "1 — 4",
      "Duree": "60 — 120",
      "Ages": "14+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Aeon's End",
      "Categories": "Jeu de Cartes",
      "Themes": "Médiéval Fantastique,Monstres",
      "Mecanismes": "Coopération,Deck building,Gestion de main,Pouvoir",
      "Editeurs": "Matagot",
      "Auteurs": "Kevin Riley",
      "Illustrateurs": "Gong Studios,Scott Hartman,Stephanie Gustafsson",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1720636723/jpg/ax/23357.jpg"
    },
    {
      "ID": 57209,
      "Titre": "Alice is Missing",
      "Sous-titre": "",
      "Edition": 2022,
      "Type": "basegame",
      "EAN": "9791094150504",
      "Prix": "18",
      "Joueurs": "3 — 5",
      "Duree": "120+",
      "Ages": "16+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Alice is Missing",
      "Categories": "Jeu De Rôle",
      "Themes": "Enfant,Enquêtes & Mystères",
      "Mecanismes": "Communication Restreinte,Coopération,Narration,Rôle,Scénario",
      "Editeurs": "Origames",
      "Auteurs": "Spenser Starke",
      "Illustrateurs": "Julianne Griepp",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1721374810/jpg/cf/57209.jpg"
    },
    {
      "ID": 4947,
      "Titre": "Bang!",
      "Sous-titre": "",
      "Edition": 2011,
      "Type": "basegame",
      "EAN": "3558380005605",
      "Prix": "20",
      "Joueurs": "4 — 7",
      "Duree": "20 — 40",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Bang!",
      "Categories": "Jeu de Cartes",
      "Themes": "Far West",
      "Mecanismes": "Affrontement Direct,Combinaison,Équipe,Gestion de main,Rôle secret",
      "Editeurs": "Dv Giochi",
      "Auteurs": "Emiliano Sciarra",
      "Illustrateurs": "Alex Pierangelini",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1709818721/jpg/ae/4947.jpg"
    },
    {
      "ID": 5169,
      "Titre": "Boggle",
      "Sous-titre": "",
      "Edition": 1974,
      "Type": "basegame",
      "EAN": "",
      "Prix": "0",
      "Joueurs": "1 — 8",
      "Duree": "30",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Boggle",
      "Categories": "Jeu de lettres",
      "Themes": "Abstrait,Lettres",
      "Mecanismes": "Logique",
      "Editeurs": "Capiépa",
      "Auteurs": "Alan Turoff",
      "Illustrateurs": "",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1501794861/300/af/5169.png"
    },
    {
      "ID": 16613,
      "Titre": "Bohnanza",
      "Sous-titre": "",
      "Edition": 2009,
      "Type": "basegame",
      "EAN": "3421272104017",
      "Prix": "10",
      "Joueurs": "2 — 5",
      "Duree": "60",
      "Ages": "12+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Bohnanza",
      "Categories": "Jeu de Cartes",
      "Themes": "Commerce,Fruits & légumes",
      "Mecanismes": "Collection,Commerce,Échange & Troc,Gestion de main",
      "Editeurs": "Gigamic",
      "Auteurs": "Uwe Rosenberg",
      "Illustrateurs": "Björn Pertoft",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1655106402/300/aq/16613.png"
    },
    {
      "ID": 35740,
      "Titre": "Carcassonne",
      "Sous-titre": "",
      "Edition": 2016,
      "Type": "basegame",
      "EAN": "8435407619968",
      "Prix": "24,95",
      "Joueurs": "2 — 5",
      "Duree": "30 — 60",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "Carcassonne",
      "Gammes": "Carcassonne",
      "Categories": "Jeu de tuiles",
      "Themes": "Médiéval,Ville",
      "Mecanismes": "Blocage,Connexion,Majorité,Placement,Pose de tuiles",
      "Editeurs": "Hans Im Glück,Z-Man Games",
      "Auteurs": "Klaus-Jürgen Wrede",
      "Illustrateurs": "Anne Pätzke,Chris Quilliams",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1686407860/jpg/bj/35740.jpg"
    },
    {
      "ID": 19557,
      "Titre": "Citadelles",
      "Sous-titre": "",
      "Edition": 2016,
      "Type": "basegame",
      "EAN": "3558380038924,8433407639126",
      "Prix": "15",
      "Joueurs": "2 — 7",
      "Duree": "30 — 60",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Citadelles",
      "Categories": "Jeu de Cartes",
      "Themes": "Médiéval Fantastique",
      "Mecanismes": "Bluff,Choix multiples,Choix simultanés,Construction,Draft,Gestion de main,Pouvoir",
      "Editeurs": "Edge Entertainment",
      "Auteurs": "Bruno Faidutti",
      "Illustrateurs": "Didier Graffet,Florence Magnin,Jean-Louis Mourier,Julien Delval",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1699855771/300/at/19557.png"
    },
    {
      "ID": 3648,
      "Titre": "City of Horror",
      "Sous-titre": "",
      "Edition": 2012,
      "Type": "basegame",
      "EAN": "",
      "Prix": "50",
      "Joueurs": "3 — 6",
      "Duree": "60",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "City of Horror",
      "Categories": "Jeu de plateau",
      "Themes": "Horreur,Survie,Zombies",
      "Mecanismes": "Dans Ta Face,Diplomatie,Négociation,Trahison",
      "Editeurs": "Repos Production",
      "Auteurs": "Nicolas Normandon",
      "Illustrateurs": "Miguel Coimbra",
      "Date-achat": "2022-01-22",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1668717759/300/ad/3648.png"
    },
    {
      "ID": 23635,
      "Titre": "Coimbra",
      "Sous-titre": "",
      "Edition": 2018,
      "Type": "basegame",
      "EAN": "4061897521104",
      "Prix": "44",
      "Joueurs": "2 — 4",
      "Duree": "60 — 90",
      "Ages": "14+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Coimbra",
      "Categories": "Jeu de dés",
      "Themes": "Portugal,Renaissance,Ville",
      "Mecanismes": "Collection,Draft,Jet De Dés",
      "Editeurs": "Eggertspiele",
      "Auteurs": "Flaminia Brasini,Virginio Gigli",
      "Illustrateurs": "Chris Quilliams",
      "Date-achat": "2022-01-22",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1641141840/300/ax/23635.png"
    },
    {
      "ID": 73844,
      "Titre": "Courtisans",
      "Sous-titre": "",
      "Edition": 2024,
      "Type": "basegame",
      "EAN": "3760273010423",
      "Prix": "17,9",
      "Joueurs": "2 — 5",
      "Duree": "20 — 30",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "",
      "Categories": "Jeu de Cartes",
      "Themes": "Médiéval,Royauté",
      "Mecanismes": "Chance & Hasard,Choix multiples,Collection,Dans Ta Face,Majorité,Placement de cartes,Pouvoir",
      "Editeurs": "Catch Up Games",
      "Auteurs": "Anthony Perone,Romaric Galonnier",
      "Illustrateurs": "Noëmie Chevalier",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1721223601/jpg/cv/73844.jpg"
    },
    {
      "ID": 7225,
      "Titre": "Cyclades",
      "Sous-titre": "",
      "Edition": 2009,
      "Type": "basegame",
      "EAN": "3760146642010",
      "Prix": "49",
      "Joueurs": "2 — 5",
      "Duree": "90",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Cyclades",
      "Categories": "Jeu de plateau",
      "Themes": "Antiquité,Grèce,Guerre,Les îles,Monstres,Mythologie",
      "Mecanismes": "Conquête,Contrôle de zone,Enchères,Gestion,Jet De Dés,Majorité,Plateau modulaire",
      "Editeurs": "Matagot",
      "Auteurs": "Bruno Cathala,Ludovic Maublanc",
      "Illustrateurs": "Miguel Coimbra",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1672267292/300/ah/7225.png"
    },
    {
      "ID": 28270,
      "Titre": "Dany",
      "Sous-titre": "",
      "Edition": 2019,
      "Type": "basegame",
      "EAN": "3760290560000",
      "Prix": "15,9",
      "Joueurs": "3 — 8",
      "Duree": "30",
      "Ages": "16+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Dany",
      "Categories": "Jeu de Cartes",
      "Themes": "Abstrait,Onirique",
      "Mecanismes": "Bluff,Déduction,Rôle",
      "Editeurs": "Grrre Games",
      "Auteurs": "Phil Vizcarro",
      "Illustrateurs": "Bengal",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1611701745/300/bc/28270.png"
    },
    {
      "ID": 1385,
      "Titre": "Dead of Winter",
      "Sous-titre": "À la croisée des chemins",
      "Edition": 2014,
      "Type": "basegame",
      "EAN": "0688623420001,8435407621831",
      "Prix": "59",
      "Joueurs": "2 — 5",
      "Duree": "60 — 120",
      "Ages": "13+",
      "Langues": "français,anglais",
      "Univers": "",
      "Gammes": "Dead Of Winter",
      "Categories": "Jeu de plateau",
      "Themes": "Horreur,Post-apocalyptique,Survie,Zombies",
      "Mecanismes": "Bluff,Coopération,Diplomatie,Narration,Objectif secret,Points d'action,Rôle secret,Semi-coopération,Trahison",
      "Editeurs": "Filosofia,Plaid Hat Games",
      "Auteurs": "Isaac Vega,Jonathan Gilmour",
      "Illustrateurs": "Fernanda Suarez",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1714634441/300/ab/1385.png"
    },
    {
      "ID": 28994,
      "Titre": "Dig your way out",
      "Sous-titre": "",
      "Edition": 2019,
      "Type": "basegame",
      "EAN": "3770003625612",
      "Prix": "35",
      "Joueurs": "2 — 6",
      "Duree": "40 — 45",
      "Ages": "16+",
      "Langues": "français,anglais",
      "Univers": "",
      "Gammes": "Dig your way out",
      "Categories": "Jeu de plateau",
      "Themes": "Évasion,Gangs,Mafia,Prison",
      "Mecanismes": "Déduction,Jet De Dés,Points d'action",
      "Editeurs": "Borderline",
      "Auteurs": "David Simide",
      "Illustrateurs": "Mihajlo Dimitrievski",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1682539151/300/bc/28994.png"
    },
    {
      "ID": 259,
      "Titre": "Docteur Pilule",
      "Sous-titre": "",
      "Edition": 2016,
      "Type": "basegame",
      "EAN": "3760032260724",
      "Prix": "19",
      "Joueurs": "4 — 10",
      "Duree": "15 — 30",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Docteur Pilule",
      "Categories": "Jeu d'Ambiance,Jeu de plateau",
      "Themes": "Sciences",
      "Mecanismes": "Affrontement Direct,Déduction,Équipe,Gestion de main",
      "Editeurs": "Fantastic Lombric",
      "Auteurs": "Guillaume Brunier,Jacques Exetier,Jean-Philippe Caro",
      "Illustrateurs": "Guillaume Brunier,Jacques Exertier,Jean-Phillipe Caro",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1675687428/300/aa/259.png"
    },
    {
      "ID": 37573,
      "Titre": "Dual Powers",
      "Sous-titre": "Revolution 1917",
      "Edition": 2020,
      "Type": "basegame",
      "EAN": "3663411310631",
      "Prix": "30",
      "Joueurs": "1 — 2",
      "Duree": "30 — 60",
      "Ages": "13+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Dual Powers",
      "Categories": "Jeu de plateau",
      "Themes": "Guerre,Historique,Politique,Russie",
      "Mecanismes": "Conquête,Déduction,Gestion de main",
      "Editeurs": "Don't Panic Games",
      "Auteurs": "Brett Myers",
      "Illustrateurs": "Kwanchai Moriya,Luis Francisco",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1714974273/jpg/ak/10757.jpg"
    },
    {
      "ID": 21314,
      "Titre": "Exit - La Cabane Abandonnée",
      "Sous-titre": "",
      "Edition": 2017,
      "Type": "basegame",
      "EAN": "3760175514395",
      "Prix": "12,5",
      "Joueurs": "1 — 6",
      "Duree": "60 — 120",
      "Ages": "12+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Exit",
      "Categories": "Escape Game",
      "Themes": "Enquêtes & Mystères,Nature",
      "Mecanismes": "Altération de Matériel,Coopération,Déduction,Défis,Énigme,Logique,Observation,Réflexion",
      "Editeurs": "Iello,Kosmos",
      "Auteurs": "Inka Brand,Markus Brand",
      "Illustrateurs": "Franz Vohwinkel",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1709809364/300/av/21314.png"
    },
    {
      "ID": 72786,
      "Titre": "Flowers",
      "Sous-titre": "",
      "Edition": 2024,
      "Type": "basegame",
      "EAN": "3760400210009",
      "Prix": "0",
      "Joueurs": "1 — 4",
      "Duree": "20",
      "Ages": "7+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Flowers",
      "Categories": "Jeu de Cartes",
      "Themes": "Chiffres,Couleurs,Végétaux",
      "Mecanismes": "Combinaison,Connexion,Placement de cartes,Stratégie",
      "Editeurs": "Actarus Editions",
      "Auteurs": "Paul-Henri Argiot",
      "Illustrateurs": "Julie Gruet",
      "Date-achat": "2024-06-27",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1721972405/jpg/cu/72786.jpg"
    },
    {
      "ID": 10757,
      "Titre": "Guillotine",
      "Sous-titre": "",
      "Edition": 2007,
      "Type": "basegame",
      "EAN": "",
      "Prix": "15",
      "Joueurs": "2 — 5",
      "Duree": "30",
      "Ages": "12+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Guillotine",
      "Categories": "Jeu de Cartes",
      "Themes": "France,Historique,Humour,Révolution Française",
      "Mecanismes": "Collection,Gestion de main,Placement de cartes,Pouvoir",
      "Editeurs": "Play Factory",
      "Auteurs": "Paul Peterson",
      "Illustrateurs": "Mike Raabe,Quinton Hoover",
      "Date-achat": "2022-01-22",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1714974273/jpg/ak/10757.jpg"
    },
    {
      "ID": 19595,
      "Titre": "Imaginarium",
      "Sous-titre": "",
      "Edition": 2018,
      "Type": "basegame",
      "EAN": "3760267990137",
      "Prix": "49",
      "Joueurs": "2 — 5",
      "Duree": "60 — 90",
      "Ages": "14+",
      "Langues": "français,anglais,allemand,japonais",
      "Univers": "Imaginarium",
      "Gammes": "Imaginarium",
      "Categories": "Jeu de plateau",
      "Themes": "Fantastique,Industrie,Onirique,Steam Punk",
      "Mecanismes": "Combinaison,Course,Gestion",
      "Editeurs": "Bombyx",
      "Auteurs": "Bruno Cathala,Florian Sirieix",
      "Illustrateurs": "Felideus Bubastis",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1705525647/300/at/19595.png"
    },
    {
      "ID": 7470,
      "Titre": "Jaipur",
      "Sous-titre": "",
      "Edition": 2009,
      "Type": "basegame",
      "EAN": "7640131630054,7640131630184",
      "Prix": "20",
      "Joueurs": "Duo",
      "Duree": "30",
      "Ages": "12+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Jaipur",
      "Categories": "Jeu de Cartes",
      "Themes": "Animaux,Chameau,Commerce,Inde",
      "Mecanismes": "Combinaison,Défausse,Duo,Gestion de main",
      "Editeurs": "Gameworks",
      "Auteurs": "Sébastien Pauchon",
      "Illustrateurs": "Alexandre Roche",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1695381204/jpg/ah/7470.jpg"
    },
    {
      "ID": 47693,
      "Titre": "Jekyll vs Hyde",
      "Sous-titre": "",
      "Edition": 2021,
      "Type": "basegame",
      "EAN": "3770000282603",
      "Prix": "16",
      "Joueurs": "Duo",
      "Duree": "20",
      "Ages": "8+",
      "Langues": "français,anglais,coréen",
      "Univers": "Jekyll & Hyde",
      "Gammes": "Jekyll vs Hyde",
      "Categories": "Jeu de Cartes",
      "Themes": "Époque Victorienne,Littérature",
      "Mecanismes": "Affrontement Direct,Asymétrie,Duo,Plis,Pouvoir",
      "Editeurs": "Mandoo Games",
      "Auteurs": "Geon-Il",
      "Illustrateurs": "Vincent Dutrait",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1713348601/jpg/bv/47693.jpg"
    },
    {
      "ID": 575,
      "Titre": "King of Tokyo",
      "Sous-titre": "",
      "Edition": 2016,
      "Type": "basegame",
      "EAN": "3760175513152",
      "Prix": "32",
      "Joueurs": "2 — 6",
      "Duree": "30",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "King of Tokyo",
      "Gammes": "King of Tokyo",
      "Categories": "Jeu de Cartes,Jeu de dés,Jeu de plateau",
      "Themes": "Asie,Japon,Monstres,Science-fiction,Tokyo,Ville",
      "Mecanismes": "Affrontement Direct,Chance & Hasard,Combinaison,Élimination,Gestion de main,Jet De Dés,Pouvoir",
      "Editeurs": "Iello",
      "Auteurs": "Richard Garfield",
      "Illustrateurs": "Anthony Wolff,Igor Polouchine,Jean-Baptiste Reynaud,Régis Torres,Romain Gaschet",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1710425437/300/aa/575.png"
    },
    {
      "ID": 22916,
      "Titre": "Kitchen Rush",
      "Sous-titre": "",
      "Edition": 2017,
      "Type": "basegame",
      "EAN": "3770005193133",
      "Prix": "55",
      "Joueurs": "1 — 4",
      "Duree": "30 — 45",
      "Ages": "12+",
      "Langues": "français,anglais",
      "Univers": "",
      "Gammes": "Kitchen Rush",
      "Categories": "Jeu de plateau",
      "Themes": "Cuisine,Restaurant",
      "Mecanismes": "Choix simultanés,Coopération,Gestion,Placement d'ouvriers,Rapidité,Solo,Temps réel",
      "Editeurs": "Artipia Games,Geek Attitude Games",
      "Auteurs": "Dávid Turczi,Vangelis Bagiartakis",
      "Illustrateurs": "Gong Studios",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1622966443/300/aw/22916.png"
    },
    {
      "ID": 4212,
      "Titre": "La Guerre des Moutons",
      "Sous-titre": "",
      "Edition": 2002,
      "Type": "basegame",
      "EAN": "3558380000235",
      "Prix": "20",
      "Joueurs": "2 — 4",
      "Duree": "30",
      "Ages": "7+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "La Guerre Des Moutons",
      "Categories": "Jeu de plateau",
      "Themes": "Animaux,Chasse,Loup,Moutons",
      "Mecanismes": "Bluff,Gestion de main,Placement,Pose de tuiles",
      "Editeurs": "Asmodee,Lui-Même",
      "Auteurs": "Philippe Des Pallières",
      "Illustrateurs": "François Bruel",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1682247334/300/ae/4212.png"
    },
    {
      "ID": 15455,
      "Titre": "Le Poker des cafards",
      "Sous-titre": "",
      "Edition": 2011,
      "Type": "basegame",
      "EAN": "3421272106813",
      "Prix": "11,9",
      "Joueurs": "2 — 6",
      "Duree": "15",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "De cafards",
      "Gammes": "Le Poker des Cafards",
      "Categories": "Jeu de Cartes",
      "Themes": "Animaux,Araignées,Crapaud,Insectes,Mouche,Rats",
      "Mecanismes": "Bluff,Chance & Hasard,Collection",
      "Editeurs": "Drei Magier Spiele,Gigamic",
      "Auteurs": "Jacques Zeimet",
      "Illustrateurs": "Rolf Vogt",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1689441398/300/ap/15455.png"
    },
    {
      "ID": 70810,
      "Titre": "Le Roy des Ribauds",
      "Sous-titre": "",
      "Edition": 2024,
      "Type": "basegame",
      "EAN": "9782355746826",
      "Prix": "8,9",
      "Joueurs": "Duo",
      "Duree": "10 — 15",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Micro-Game Matagot",
      "Categories": "Jeu de Cartes",
      "Themes": "Bande dessinée,Médiéval",
      "Mecanismes": "Placement de cartes,Pouvoir,Stratégie",
      "Editeurs": "Matagot",
      "Auteurs": "Erwann Ricord",
      "Illustrateurs": "Ronan Toulhoat",
      "Date-achat": "2024-06-27",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1712076118/jpg/cs/70810.jpg"
    },
    {
      "ID": 4113,
      "Titre": "Le Trône de Fer",
      "Sous-titre": "Le jeu de plateau",
      "Edition": 2011,
      "Type": "basegame",
      "EAN": "8435407600010",
      "Prix": "60",
      "Joueurs": "3 — 6",
      "Duree": "150",
      "Ages": "14+",
      "Langues": "français",
      "Univers": "Game of Thrones",
      "Gammes": "Le Trône de Fer JDP",
      "Categories": "Jeu de plateau",
      "Themes": "Fantastique,Guerre,Médiéval",
      "Mecanismes": "Affrontement Direct,Choix simultanés,Conquête,Déduction,Déplacement,Diplomatie,Enchères à poing fermé,Programmation,Trahison",
      "Editeurs": "Edge Entertainment,Fantasy Flight Games",
      "Auteurs": "Christian T. Petersen",
      "Illustrateurs": "",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover": "https://www.myludo.fr/img/jeux/1702304393/300/ae/4113.png"
    },
    {
      "ID": 28768,
      "Titre": "Le Trône de Fer  - Mère des Dragons",
      "Sous-titre": "Le jeu de plateau",
      "Edition": 2019,
      "Type": "extension",
      "EAN": "8435407622944",
      "Prix": "35,9",
      "Joueurs": "3 — 8",
      "Duree": "150",
      "Ages": "12+",
      "Langues": "français",
      "Univers": "Game of Thrones",
      "Gammes": "Le Trône de Fer JDP",
      "Categories": "Jeu de plateau",
      "Themes": "Fantastique,Guerre,Médiéval",
      "Mecanismes": "Affrontement Direct,Choix simultanés,Conquête,Déduction,Déplacement,Diplomatie,Enchères à poing fermé,Programmation,Trahison",
      "Editeurs": "Fantasy Flight Games",
      "Auteurs": "Christian T. Petersen",
      "Illustrateurs": "",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1702304313/300/bc/28768.png"
    },
    {
      "ID": 4484,
      "Titre": "Les Aventuriers du Rail",
      "Sous-titre": "",
      "Edition": 2008,
      "Type": "basegame",
      "EAN": "0824968717813",
      "Prix": "40",
      "Joueurs": "2 — 5",
      "Duree": "45",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Les Aventuriers Du Rail",
      "Categories": "Jeu de plateau",
      "Themes": "Trains,Transport & voyage",
      "Mecanismes": "Collection,Connexion,Objectif secret,Pioche,Placement",
      "Editeurs": "Days Of Wonder",
      "Auteurs": "Alan R. Moon",
      "Illustrateurs": "Julien Delval",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1686407759/300/ae/4484.png"
    },
    {
      "ID": 24737,
      "Titre": "Les Aventuriers du Rail - New York",
      "Sous-titre": "",
      "Edition": 2018,
      "Type": "basegame",
      "EAN": "0824968200605",
      "Prix": "20",
      "Joueurs": "2 — 4",
      "Duree": "10 — 15",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Les Aventuriers Du Rail",
      "Categories": "Jeu de plateau",
      "Themes": "Amérique,New York,Trains,Transport & voyage,Ville",
      "Mecanismes": "Collection,Connexion,Objectif secret,Pioche,Placement",
      "Editeurs": "Days Of Wonder",
      "Auteurs": "Alan R. Moon",
      "Illustrateurs": "Julien Delval",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1688733486/300/ay/24737.png"
    },
    {
      "ID": 12563,
      "Titre": "Les Colocs",
      "Sous-titre": "",
      "Edition": 2006,
      "Type": "basegame",
      "EAN": "9781556344763",
      "Prix": "21",
      "Joueurs": "2 — 5",
      "Duree": "60",
      "Ages": "18+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Les Colocs",
      "Categories": "Jeu de Cartes",
      "Themes": "Adulte,Humour",
      "Mecanismes": "",
      "Editeurs": "Steve Jackson Games,Ubik",
      "Auteurs": "Jon Darbro",
      "Illustrateurs": "John Kovalic",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1702838781/300/am/12563.png"
    },
    {
      "ID": 4385,
      "Titre": "Les Loups-Garous de Thiercelieux : Ten Years After",
      "Sous-titre": "",
      "Edition": 2011,
      "Type": "basegame",
      "EAN": "",
      "Prix": "17",
      "Joueurs": "8 — 18",
      "Duree": "30",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Les Loups-Garous de Thiercelieux",
      "Categories": "",
      "Themes": "Fantastique,Loups-garous,Médiéval,Monstres",
      "Mecanismes": "Déduction,Élimination,Narration,Objectif secret,Rôle secret",
      "Editeurs": "Lui-Même",
      "Auteurs": "Hervé Marly,Philippe Des Pallières",
      "Illustrateurs": "Alexios Tjoyas",
      "Date-achat": "2022-01-22",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1589576987/300/ae/4385.png"
    },
    {
      "ID": 1280,
      "Titre": "Les Poilus",
      "Sous-titre": "L'amitié plus forte que la guerre ?",
      "Edition": 2015,
      "Type": "basegame",
      "EAN": "3760205230493",
      "Prix": "19,5",
      "Joueurs": "2 — 5",
      "Duree": "30",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Les Poilus",
      "Categories": "Jeu de Cartes",
      "Themes": "Guerre,Historique,WW1",
      "Mecanismes": "Chance & Hasard,Combinaison,Coopération,Pioche,Prise de risque",
      "Editeurs": "Edge Entertainment,Sweet Games,Sweet November",
      "Auteurs": "Fabien Riffaud,Juan Rodriguez",
      "Illustrateurs": "Tignous",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1688447732/jpg/ab/1280.jpg"
    },
    {
      "ID": 21956,
      "Titre": "Les Poilus - Aux Ordres !",
      "Sous-titre": "",
      "Edition": 2016,
      "Type": "extension",
      "EAN": "3760205230523",
      "Prix": "0",
      "Joueurs": "2 — 5",
      "Duree": "30 — 60",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Les Poilus",
      "Categories": "Jeu de Cartes",
      "Themes": "Guerre,Historique,WW1",
      "Mecanismes": "Chance & Hasard,Combinaison,Coopération,Pioche,Prise de risque",
      "Editeurs": "Sweet November",
      "Auteurs": "Fabien Riffaud,Juan Rodriguez",
      "Illustrateurs": "Tignous",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1706112063/300/av/21956.png"
    },
    {
      "ID": 55766,
      "Titre": "Level 10",
      "Sous-titre": "",
      "Edition": 2022,
      "Type": "basegame",
      "EAN": "3760146643284",
      "Prix": "9,9",
      "Joueurs": "1 — 5",
      "Duree": "20",
      "Ages": "8+",
      "Langues": "français,anglais",
      "Univers": "",
      "Gammes": "Pixel Collection",
      "Categories": "Jeu de Cartes",
      "Themes": "Jeu vidéo",
      "Mecanismes": "Argumentation,Solo",
      "Editeurs": "Matagot",
      "Auteurs": "Hisashi Hayashi",
      "Illustrateurs": "Francisco Coda",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1699292846/jpg/cd/55766.jpg"
    },
    {
      "ID": 1108,
      "Titre": "Mafia de Cuba",
      "Sous-titre": "",
      "Edition": 2015,
      "Type": "basegame",
      "EAN": "3558380028857",
      "Prix": "25",
      "Joueurs": "6 — 12",
      "Duree": "20",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Mafia de Cuba",
      "Categories": "Jeu d'Ambiance",
      "Themes": "Années 50,Enquêtes & Mystères,Espionnage,Mafia,Pierres Précieuses,Voleur",
      "Mecanismes": "Bluff,Déduction,Élimination,Rôle secret",
      "Editeurs": "Lui-Même",
      "Auteurs": "Loïc Lamy,Philippe Des Pallières",
      "Illustrateurs": "Thomas Vuarchex",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1662711950/300/ab/1108.png"
    },
    {
      "ID": 42016,
      "Titre": "MicroMacro Crime City",
      "Sous-titre": "",
      "Edition": 2020,
      "Type": "basegame",
      "EAN": "3770000282580",
      "Prix": "24,95",
      "Joueurs": "1 — 4",
      "Duree": "15 — 45",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "MicroMacro Crime City",
      "Categories": "Jeu d'Observation",
      "Themes": "Criminalité,Enquêtes & Mystères,Objets,Vie quotidienne,Ville",
      "Mecanismes": "Coopération,Déduction,Observation,Scénario",
      "Editeurs": "Blackrock Games,Spielwiese",
      "Auteurs": "Johannes Sich",
      "Illustrateurs": "Daniel Goll,Johannes Sich",
      "Date-achat": "2022-05-23",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1704270112/jpg/bq/42016.jpg"
    },
    {
      "ID": 50055,
      "Titre": "MicroMacro Crime City - Full House",
      "Sous-titre": "",
      "Edition": 2021,
      "Type": "basegame",
      "EAN": "3770000282689",
      "Prix": "25",
      "Joueurs": "1 — 4",
      "Duree": "15 — 45",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "MicroMacro Crime City",
      "Categories": "Jeu D'Enquête",
      "Themes": "Enquêtes & Mystères",
      "Mecanismes": "Campagne,Coopération,Déduction,Équipe,Narration,Scénario,Solo",
      "Editeurs": "Spielwiese",
      "Auteurs": "Johannes Sich",
      "Illustrateurs": "Johannes Sich",
      "Date-achat": "2023-03-26",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1696055750/jpg/by/50055.jpg"
    },
    {
      "ID": 36636,
      "Titre": "Mini Rogue",
      "Sous-titre": "",
      "Edition": 2021,
      "Type": "basegame",
      "EAN": "3770009354530",
      "Prix": "17",
      "Joueurs": "1 — 2",
      "Duree": "30",
      "Ages": "14+",
      "Langues": "français,anglais",
      "Univers": "",
      "Gammes": "Mini Rogue",
      "Categories": "Jeu de Cartes",
      "Themes": "Aventure,Donjon,Exploration,Fantastique",
      "Mecanismes": "Exploration,Jet De Dés,Prise de risque,Rôle,Solo",
      "Editeurs": "Mountain Gold Games,Nuts! Publishing",
      "Auteurs": "Gabriel Gendron,Paolo Di Stefano",
      "Illustrateurs": "Gabriel Gendron",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1710003860/300/bk/36636.png"
    },
    {
      "ID": 52674,
      "Titre": "Mr. Jack - London",
      "Sous-titre": "",
      "Edition": 2021,
      "Type": "basegame",
      "EAN": "7612577001521",
      "Prix": "27",
      "Joueurs": "Duo",
      "Duree": "30",
      "Ages": "8+",
      "Langues": "français,allemand,néerlandais",
      "Univers": "Mr. Jack,Sherlock Holmes",
      "Gammes": "Mr. Jack",
      "Categories": "Jeu de plateau",
      "Themes": "Angleterre,Enquêtes & Mystères,Londres,Ville",
      "Mecanismes": "Asymétrie,Bluff,Capture,Déduction,Duo,Jeu caché,Mouvement de point à point,Objectif secret,Prise de risque",
      "Editeurs": "Hurrican",
      "Auteurs": "Bruno Cathala,Ludovic Maublanc",
      "Illustrateurs": "Piérô",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1671982538/jpg/ca/52674.jpg"
    },
    {
      "ID": 37546,
      "Titre": "Mysterium Park",
      "Sous-titre": "",
      "Edition": 2020,
      "Type": "basegame",
      "EAN": "3558380076568",
      "Prix": "25",
      "Joueurs": "2 — 6",
      "Duree": "28",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "Mysterium",
      "Gammes": "Mysterium Park",
      "Categories": "Jeu de Cartes,Jeu de plateau",
      "Themes": "Cirque,Enquêtes & Mystères,Fantastique,Fantômes & Esprits,Loisirs",
      "Mecanismes": "Association,Asymétrie,Coopération,Déduction,Énigme,Narration",
      "Editeurs": "Libellud",
      "Auteurs": "Oleg Sidorenko,Oleksandr Nevskiy",
      "Illustrateurs": "M81 Studio,Xavier Collette",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1693469769/300/bl/37546.png"
    },
    {
      "ID": 23234,
      "Titre": "New Angeles",
      "Sous-titre": "",
      "Edition": 2017,
      "Type": "basegame",
      "EAN": "8435407614260",
      "Prix": "60",
      "Joueurs": "4 — 6",
      "Duree": "120",
      "Ages": "14+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "New Angeles",
      "Categories": "Jeu de plateau",
      "Themes": "",
      "Mecanismes": "",
      "Editeurs": "Fantasy Flight Games",
      "Auteurs": "James Kniffen",
      "Illustrateurs": "",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1715619332/300/ax/23234.png"
    },
    {
      "ID": 16886,
      "Titre": "Perudo",
      "Sous-titre": "",
      "Edition": 2003,
      "Type": "basegame",
      "EAN": "",
      "Prix": "19",
      "Joueurs": "2 — 6",
      "Duree": "20",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Perudo",
      "Categories": "Jeu de dés",
      "Themes": "Abstrait,Chiffres",
      "Mecanismes": "Bluff,Chance & Hasard,Collection,Élimination,Jet De Dés,Mémorisation",
      "Editeurs": "Asmodee",
      "Auteurs": "Alfredo Fernandini,Cosmo Fry",
      "Illustrateurs": "Thierry Masson",
      "Date-achat": "2022-01-22",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1709030352/jpg/aq/16886.jpg"
    },
    {
      "ID": 10787,
      "Titre": "Petits meurtres & faits divers",
      "Sous-titre": "",
      "Edition": 2007,
      "Type": "basegame",
      "EAN": "3558380002666",
      "Prix": "30",
      "Joueurs": "4 — 7",
      "Duree": "45",
      "Ages": "12+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Petits meurtres & faits divers",
      "Categories": "Jeu d'Ambiance",
      "Themes": "Contemporain,Enquêtes & Mystères,Humour,Vocabulaire",
      "Mecanismes": "Créativité,Déduction,Improvisation,Mémorisation,Narration,Questions & Réponses",
      "Editeurs": "Asmodee",
      "Auteurs": "Hervé Marly",
      "Illustrateurs": "",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1662719251/300/ak/10787.png"
    },
    {
      "ID": 9712,
      "Titre": "Privacy",
      "Sous-titre": "",
      "Edition": 2008,
      "Type": "basegame",
      "EAN": "3421272103218",
      "Prix": "20",
      "Joueurs": "3 — 12",
      "Duree": "45",
      "Ages": "18+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Privacy",
      "Categories": "Jeu d'Ambiance,Jeu De Connaissances",
      "Themes": "Adulte,Humour",
      "Mecanismes": "Guessing,Pari,Questions & Réponses",
      "Editeurs": "Gigamic",
      "Auteurs": "Reinhard Staupe",
      "Illustrateurs": "",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1654071029/300/aj/9712.png"
    },
    {
      "ID": 48693,
      "Titre": "Red Rising",
      "Sous-titre": "",
      "Edition": 2021,
      "Type": "basegame",
      "EAN": "3760146649231",
      "Prix": "45",
      "Joueurs": "1 — 6",
      "Duree": "45 — 60",
      "Ages": "14+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Red Rising",
      "Categories": "Jeu de Cartes",
      "Themes": "Dystopie,Littérature,Science-fiction",
      "Mecanismes": "Combinaison,Gestion de main,Pouvoir",
      "Editeurs": "Matagot",
      "Auteurs": "Alexander Schmidt,Jamey Stegmaier",
      "Illustrateurs": "Jacqui Davis,Justin Wong",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1714853896/300/bw/48693.png"
    },
    {
      "ID": 58686,
      "Titre": "Resonance",
      "Sous-titre": "",
      "Edition": 2023,
      "Type": "basegame",
      "EAN": "",
      "Prix": "0",
      "Joueurs": "3 — 8",
      "Duree": "20 — 40",
      "Ages": "10+",
      "Langues": "anglais",
      "Univers": "",
      "Gammes": "",
      "Categories": "Jeu de Cartes",
      "Themes": "Fantastique,Sorcellerie",
      "Mecanismes": "Gestion de main",
      "Editeurs": "Dtda Games",
      "Auteurs": "Serge Matsumoto",
      "Illustrateurs": "Manon Potier",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1658868014/jpg/cg/58686.jpg"
    },
    {
      "ID": 10258,
      "Titre": "Salade de Cafards",
      "Sous-titre": "",
      "Edition": 2011,
      "Type": "basegame",
      "EAN": "3421272106912",
      "Prix": "10",
      "Joueurs": "2 — 6",
      "Duree": "20",
      "Ages": "6+",
      "Langues": "français",
      "Univers": "De cafards",
      "Gammes": "Salade de Cafards",
      "Categories": "Jeu d'Ambiance,Jeu de Cartes",
      "Themes": "Fruits & légumes",
      "Mecanismes": "Défausse,Rapidité",
      "Editeurs": "Drei Magier Spiele,Gigamic",
      "Auteurs": "Jacques Zeimet",
      "Illustrateurs": "Johann Rüttinger,Lena Kappler,Rolf Vogt",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1622965999/300/ak/10258.png"
    },
    {
      "ID": 561,
      "Titre": "Secret Hitler",
      "Sous-titre": "",
      "Edition": 2016,
      "Type": "basegame",
      "EAN": "0711746875073",
      "Prix": "39,9",
      "Joueurs": "5 — 10",
      "Duree": "30 — 60",
      "Ages": "14+",
      "Langues": "français,anglais,allemand,espagnol,italien",
      "Univers": "",
      "Gammes": "Secret Hitler",
      "Categories": "Jeu de Cartes,Print & Play",
      "Themes": "Historique,Nazis",
      "Mecanismes": "Bluff,Déduction,Rôle secret",
      "Editeurs": "Goat Wolf & Cabbage",
      "Auteurs": "Max Temkin,Mike Boxleiter,Tommy Maranges",
      "Illustrateurs": "Mackenzie Schubert",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1681394877/300/aa/561.png"
    },
    {
      "ID": 42051,
      "Titre": "Shamans",
      "Sous-titre": "",
      "Edition": 2020,
      "Type": "basegame",
      "EAN": "3616450005327",
      "Prix": "20",
      "Joueurs": "3 — 5",
      "Duree": "30 — 60",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "",
      "Categories": "Jeu de Cartes",
      "Themes": "Fantastique,Folklore",
      "Mecanismes": "Gestion de main,Rôle secret",
      "Editeurs": "Studio H",
      "Auteurs": "Cédrick Chaboussit",
      "Illustrateurs": "Maud Chalmel",
      "Date-achat": "2023-03-26",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1705480140/300/bq/42051.png"
    },
    {
      "ID": 33366,
      "Titre": "SHASN",
      "Sous-titre": "",
      "Edition": 2019,
      "Type": "basegame",
      "EAN": "",
      "Prix": "0",
      "Joueurs": "3 — 5",
      "Duree": "90 — 120",
      "Ages": "12+",
      "Langues": "anglais",
      "Univers": "",
      "Gammes": "SHASN",
      "Categories": "Jeu de plateau",
      "Themes": "Politique",
      "Mecanismes": "Conquête,Contrôle de zone,Pouvoir,Simulation",
      "Editeurs": "Memesys Culture Lab",
      "Auteurs": "Zain Memon",
      "Illustrateurs": "Soumik Lahiri",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1631205918/300/bh/33366.png"
    },
    {
      "ID": 1875,
      "Titre": "Splendor",
      "Sous-titre": "",
      "Edition": 2014,
      "Type": "basegame",
      "EAN": "3558380020974,3558380022251",
      "Prix": "29",
      "Joueurs": "2 — 4",
      "Duree": "30",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Splendor",
      "Categories": "Jeu de Cartes",
      "Themes": "Commerce,Pierres Précieuses,Renaissance",
      "Mecanismes": "Blocage,Combinaison,Commerce,Échange & Troc,Gestion,Récolte",
      "Editeurs": "Space Cowboys",
      "Auteurs": "Marc André",
      "Illustrateurs": "Pascal Quidault",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1696153038/jpg/ab/1875.jpg"
    },
    {
      "ID": 6290,
      "Titre": "Super Comics",
      "Sous-titre": "",
      "Edition": 2010,
      "Type": "basegame",
      "EAN": "0807658000099",
      "Prix": "16",
      "Joueurs": "3 — 20",
      "Duree": "20",
      "Ages": "12+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Super Comics",
      "Categories": "Jeu de Cartes",
      "Themes": "Super-héros",
      "Mecanismes": "Défis",
      "Editeurs": "Le Scorpion Masqué",
      "Auteurs": "Christian Lemay,Roberto Fraga",
      "Illustrateurs": "",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1696320099/300/ag/6290.png"
    },
    {
      "ID": 29888,
      "Titre": "Super Fantasy Brawl",
      "Sous-titre": "",
      "Edition": 2020,
      "Type": "basegame",
      "EAN": "0618528205663",
      "Prix": "45",
      "Joueurs": "2 — 4",
      "Duree": "20 — 45",
      "Ages": "10+",
      "Langues": "français,anglais",
      "Univers": "Fabulosa",
      "Gammes": "Super Fantasy Brawl",
      "Categories": "Jeu de figurines",
      "Themes": "Fantasy",
      "Mecanismes": "Affrontement Direct,Déplacement,Gestion de main,Pouvoir,Programmation",
      "Editeurs": "Mythic Games",
      "Auteurs": "Jochen Eisenhuth",
      "Illustrateurs": "Bayard Wu,Johannes Helgeson,Stéphane Gantiez",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1678648897/300/bd/29888.png"
    },
    {
      "ID": 32958,
      "Titre": "Super Fantasy Brawl - Art of War",
      "Sous-titre": "",
      "Edition": 2020,
      "Type": "extension",
      "EAN": "",
      "Prix": "20",
      "Joueurs": "Duo",
      "Duree": "15 — 45",
      "Ages": "10+",
      "Langues": "français,anglais",
      "Univers": "Fabulosa",
      "Gammes": "Super Fantasy Brawl",
      "Categories": "Jeu de figurines",
      "Themes": "Fantasy",
      "Mecanismes": "Déplacement,Gestion de main,Pouvoir,Programmation",
      "Editeurs": "Mythic Games",
      "Auteurs": "Jochen Eisenhuth",
      "Illustrateurs": "Bayard Wu,Johannes Helgeson,Stéphane Gantiez",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1678648224/jpg/bg/32958.jpg"
    },
    {
      "ID": 32957,
      "Titre": "Super Fantasy Brawl - Circle of Blood",
      "Sous-titre": "",
      "Edition": 2020,
      "Type": "extension",
      "EAN": "",
      "Prix": "20",
      "Joueurs": "Duo",
      "Duree": "15 — 45",
      "Ages": "10+",
      "Langues": "français,anglais",
      "Univers": "Fabulosa",
      "Gammes": "Super Fantasy Brawl",
      "Categories": "Jeu de figurines",
      "Themes": "Fantasy",
      "Mecanismes": "Déplacement,Gestion de main,Pouvoir,Programmation",
      "Editeurs": "Mythic Games",
      "Auteurs": "Jochen Eisenhuth",
      "Illustrateurs": "Bayard Wu,Johannes Helgeson,Stéphane Gantiez",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1678648186/jpg/bg/32957.jpg"
    },
    {
      "ID": 32956,
      "Titre": "Super Fantasy Brawl - Force of nature",
      "Sous-titre": "",
      "Edition": 2019,
      "Type": "extension",
      "EAN": "",
      "Prix": "20",
      "Joueurs": "Duo",
      "Duree": "15 — 45",
      "Ages": "10+",
      "Langues": "français,anglais",
      "Univers": "Fabulosa",
      "Gammes": "Super Fantasy Brawl",
      "Categories": "Jeu de figurines",
      "Themes": "Fantasy",
      "Mecanismes": "Déplacement,Gestion de main,Pouvoir,Programmation",
      "Editeurs": "Mythic Games",
      "Auteurs": "Jochen Eisenhuth",
      "Illustrateurs": "Bayard Wu,Johannes Helgeson,Stéphane Gantiez",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1678648295/jpg/bg/32956.jpg"
    },
    {
      "ID": 48322,
      "Titre": "Super Fantasy Brawl - Hot Trick",
      "Sous-titre": "",
      "Edition": 2021,
      "Type": "extension",
      "EAN": "",
      "Prix": "18",
      "Joueurs": "2 — 4",
      "Duree": "15 — 45",
      "Ages": "10+",
      "Langues": "français,anglais",
      "Univers": "Fabulosa",
      "Gammes": "Super Fantasy Brawl",
      "Categories": "Jeu de figurines",
      "Themes": "Fantasy",
      "Mecanismes": "Déplacement,Gestion de main,Pouvoir,Programmation",
      "Editeurs": "Mythic Games",
      "Auteurs": "Jochen Eisenhuth",
      "Illustrateurs": "Bayard Wu,Johannes Helgeson,Stéphane Gantiez",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1678648393/jpg/bw/48322.jpg"
    },
    {
      "ID": 48323,
      "Titre": "Super Fantasy Brawl - Mental Might",
      "Sous-titre": "",
      "Edition": 2021,
      "Type": "extension",
      "EAN": "",
      "Prix": "18",
      "Joueurs": "2 — 4",
      "Duree": "15 — 45",
      "Ages": "10+",
      "Langues": "français,anglais",
      "Univers": "Fabulosa",
      "Gammes": "Super Fantasy Brawl",
      "Categories": "Jeu de figurines",
      "Themes": "Fantasy",
      "Mecanismes": "Déplacement,Gestion de main,Pouvoir,Programmation",
      "Editeurs": "Mythic Games",
      "Auteurs": "Jochen Eisenhuth",
      "Illustrateurs": "Bayard Wu,Johannes Helgeson,Stéphane Gantiez",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1678648485/jpg/bw/48323.jpg"
    },
    {
      "ID": 48324,
      "Titre": "Super Fantasy Brawl - Radiant Authority",
      "Sous-titre": "",
      "Edition": 2021,
      "Type": "extension",
      "EAN": "",
      "Prix": "20",
      "Joueurs": "2 — 4",
      "Duree": "15 — 45",
      "Ages": "10+",
      "Langues": "français,anglais",
      "Univers": "Fabulosa",
      "Gammes": "Super Fantasy Brawl",
      "Categories": "Jeu de figurines",
      "Themes": "Fantasy",
      "Mecanismes": "Déplacement,Gestion de main,Pouvoir,Programmation",
      "Editeurs": "Mythic Games",
      "Auteurs": "Jochen Eisenhuth",
      "Illustrateurs": "Bayard Wu,Johannes Helgeson,Stéphane Gantiez",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1678648543/jpg/bw/48324.jpg"
    },
    {
      "ID": 21882,
      "Titre": "Sushi Go !",
      "Sous-titre": "",
      "Edition": 2014,
      "Type": "basegame",
      "EAN": "3760052141652,3760052142765",
      "Prix": "13",
      "Joueurs": "2 — 5",
      "Duree": "15",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Sushi Go",
      "Categories": "Jeu de Cartes",
      "Themes": "Alimentation,Cuisine,Japon",
      "Mecanismes": "Draft,Majorité,Prise de risque",
      "Editeurs": "Cocktail Games,Gamewright",
      "Auteurs": "Phil Walker-Harding",
      "Illustrateurs": "Nan Rangsima",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1650642029/300/av/21882.png"
    },
    {
      "ID": 23957,
      "Titre": "Sushi Go ! - Sauce Soja",
      "Sous-titre": "",
      "Edition": 2014,
      "Type": "goodie",
      "EAN": "",
      "Prix": "0",
      "Joueurs": "2 — 5",
      "Duree": "15",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Sushi Go",
      "Categories": "Jeu de Cartes",
      "Themes": "Alimentation,Cuisine",
      "Mecanismes": "Choix simultanés,Collection,Draft,Gestion de main",
      "Editeurs": "Cocktail Games,Gamewright,Reflexshop,Uplay.it Edizioni,W. Nostheide Verlag,White Goblin Games,Zoch Zum Spielen",
      "Auteurs": "Phil Walker-Harding",
      "Illustrateurs": "Nan Rangsima",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1708513859/300/ax/23957.png"
    },
    {
      "ID": 20872,
      "Titre": "Sushi Go Party!",
      "Sous-titre": "",
      "Edition": 2017,
      "Type": "basegame",
      "EAN": "4015682051147",
      "Prix": "24,95",
      "Joueurs": "2 — 8",
      "Duree": "20",
      "Ages": "8+",
      "Langues": "anglais,allemand",
      "Univers": "",
      "Gammes": "Sushi Go",
      "Categories": "Jeu de Cartes",
      "Themes": "",
      "Mecanismes": "Choix simultanés,Collection,Draft,Gestion de main",
      "Editeurs": "Gamewright",
      "Auteurs": "Phil Walker-Harding",
      "Illustrateurs": "Nan Rangsima",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1674919240/300/au/20872.png"
    },
    {
      "ID": 34089,
      "Titre": "Sushi Roll",
      "Sous-titre": "",
      "Edition": 2019,
      "Type": "basegame",
      "EAN": "3760052143199",
      "Prix": "22,5",
      "Joueurs": "2 — 5",
      "Duree": "20",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "",
      "Categories": "Jeu de dés",
      "Themes": "Alimentation",
      "Mecanismes": "Jet De Dés",
      "Editeurs": "Cocktail Games",
      "Auteurs": "Phil Walker-Harding",
      "Illustrateurs": "Nan Rangsima",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1567074817/300/bi/34089.png"
    },
    {
      "ID": 1088,
      "Titre": "T.I.M.E Stories",
      "Sous-titre": "",
      "Edition": 2015,
      "Type": "basegame",
      "EAN": "3558380031017",
      "Prix": "45",
      "Joueurs": "2 — 4",
      "Duree": "90+",
      "Ages": "12+",
      "Langues": "français",
      "Univers": "T.I.M.E Stories",
      "Gammes": "T.I.M.E Stories",
      "Categories": "Jeu de plateau",
      "Themes": "Asile,Aventure,Enquêtes & Mystères,Science-fiction,Voyage temporel",
      "Mecanismes": "Chance & Hasard,Coopération,Déplacement,Énigme,Exploration,Rôle",
      "Editeurs": "Space Cowboys",
      "Auteurs": "Manuel Rozoy,Peggy Chassenet",
      "Illustrateurs": "Benjamin Carré,David Lecossu,Pascal Quidault",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1715892843/300/ab/1088.png"
    },
    {
      "ID": 4642,
      "Titre": "Taggle",
      "Sous-titre": "",
      "Edition": 2011,
      "Type": "basegame",
      "EAN": "3760116321181",
      "Prix": "20",
      "Joueurs": "3 — 5",
      "Duree": "20",
      "Ages": "16+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Taggle",
      "Categories": "Jeu de Cartes",
      "Themes": "Humour",
      "Mecanismes": "Narration",
      "Editeurs": "Le Droit De Perdre",
      "Auteurs": "Fabien Bleuze,Yves Hirschfeld",
      "Illustrateurs": "",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1709818066/jpg/ae/4642.jpg"
    },
    {
      "ID": 37535,
      "Titre": "Tea For 2",
      "Sous-titre": "",
      "Edition": 2020,
      "Type": "basegame",
      "EAN": "3558380071297,3558380071310",
      "Prix": "20",
      "Joueurs": "Duo",
      "Duree": "30",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "Alice au pays des merveilles",
      "Gammes": "2 joueurs des Space Cowboys,Tea for 2",
      "Categories": "Jeu de Cartes",
      "Themes": "Chiffres,Contes,Littérature,Thé",
      "Mecanismes": "Affrontement Direct,Choix multiples,Deck building,destruction,Duo,Majorité,Points d'action,Pouvoir",
      "Editeurs": "Space Cowboys",
      "Auteurs": "Cédrick Chaboussit",
      "Illustrateurs": "Amandine Dugon",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1722142580/300/bl/37535.png"
    },
    {
      "ID": 61611,
      "Titre": "Trio",
      "Sous-titre": "",
      "Edition": 2023,
      "Type": "basegame",
      "EAN": "3760052143731",
      "Prix": "13",
      "Joueurs": "3 — 6",
      "Duree": "15",
      "Ages": "7+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Trio",
      "Categories": "Jeu de Cartes",
      "Themes": "Chiffres,Mexique",
      "Mecanismes": "Chance & Hasard,Collection,Mémorisation,Observation",
      "Editeurs": "Cocktail Games",
      "Auteurs": "Kaya Miyano",
      "Illustrateurs": "Laura Michaud",
      "Date-achat": "2024-06-27",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1721376199/jpg/cj/61611.jpg"
    },
    {
      "ID": 21082,
      "Titre": "Tyrants of the Underdark",
      "Sous-titre": "",
      "Edition": 2016,
      "Type": "basegame",
      "EAN": "",
      "Prix": "0",
      "Joueurs": "2 — 4",
      "Duree": "60",
      "Ages": "14+",
      "Langues": "anglais",
      "Univers": "",
      "Gammes": "Les Tyrans de l'Ombreterre",
      "Categories": "Jeu de Cartes,Jeu de figurines,Jeu de plateau",
      "Themes": "Médiéval Fantastique",
      "Mecanismes": "Conquête,Deck building",
      "Editeurs": "Gale Force Nine,Wizards Of The Coast",
      "Auteurs": "Andrew Veen,Peter Lee,Rodney Thompson",
      "Illustrateurs": "",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1620058219/300/av/21082.png"
    },
    {
      "ID": 26973,
      "Titre": "Tyrants of the Underdark - Aberrations & Undead",
      "Sous-titre": "",
      "Edition": 2017,
      "Type": "extension",
      "EAN": "",
      "Prix": "0",
      "Joueurs": "2 — 4",
      "Duree": "60",
      "Ages": "14+",
      "Langues": "anglais",
      "Univers": "",
      "Gammes": "Les Tyrans de l'Ombreterre",
      "Categories": "Jeu de Cartes,Jeu de figurines,Jeu de plateau",
      "Themes": "Fantastique,Médiéval",
      "Mecanismes": "Conquête,Deck building",
      "Editeurs": "Gale Force Nine,Wizards Of The Coast",
      "Auteurs": "Andrew Veen,Peter Lee,Rodney Thompson",
      "Illustrateurs": "",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1539274336/300/ba/26973.png"
    },
    {
      "ID": 46174,
      "Titre": "Unmatched - Combats de Légende",
      "Sous-titre": "Volume 1",
      "Edition": 2021,
      "Type": "basegame",
      "EAN": "3760175517563",
      "Prix": "35",
      "Joueurs": "2 — 4",
      "Duree": "30",
      "Ages": "9+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Unmatched",
      "Categories": "Jeu de Cartes,Jeu de figurines",
      "Themes": "Contes,Folklore,Mythologie",
      "Mecanismes": "Affrontement Direct,Asymétrie,Gestion de main,Stratégie",
      "Editeurs": "Iello",
      "Auteurs": "JR Honeycutt,Justin D. Jacobson,Rob Daviau",
      "Illustrateurs": "Oliver Barrett",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1694524697/300/bu/46174.png"
    },
    {
      "ID": 50444,
      "Titre": "Unmatched - Petit Chaperon rouge vs Beowulf",
      "Sous-titre": "",
      "Edition": 2022,
      "Type": "standalone",
      "EAN": "0376017551870",
      "Prix": "28",
      "Joueurs": "Duo",
      "Duree": "20",
      "Ages": "9+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Unmatched",
      "Categories": "Jeu de Cartes,Jeu de figurines",
      "Themes": "Contes,Fantastique,Mythologie",
      "Mecanismes": "Affrontement Direct,Asymétrie,Duo,Gestion de main,Pouvoir,Stratégie",
      "Editeurs": "Iello",
      "Auteurs": "Brian Neff,Justin D. Jacobson,Noah Cohen,Rob Daviau",
      "Illustrateurs": "Ian O'toole,Marc Aspinall",
      "Date-achat": "2022-05-23",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1658663954/jpg/by/50444.jpg"
    },
    {
      "ID": 47110,
      "Titre": "Unmatched - Robin des Bois vs Bigfoot",
      "Sous-titre": "",
      "Edition": 2021,
      "Type": "standalone",
      "EAN": "3760175517600",
      "Prix": "28",
      "Joueurs": "Duo",
      "Duree": "30 — 60",
      "Ages": "9+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Unmatched",
      "Categories": "Jeu de Cartes,Jeu de figurines",
      "Themes": "Contes,Folklore,Mythologie",
      "Mecanismes": "Affrontement Direct,Asymétrie,Duo,Gestion de main,Pouvoir,Stratégie",
      "Editeurs": "Iello",
      "Auteurs": "JR Honeycutt,Justin D. Jacobson,Rob Daviau",
      "Illustrateurs": "Oliver Barrett",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1707426111/300/bv/47110.png"
    },
    {
      "ID": 40114,
      "Titre": "Vampire La Mascarade - Vendetta",
      "Sous-titre": "",
      "Edition": 2021,
      "Type": "basegame",
      "EAN": "3760175517785",
      "Prix": "28,5",
      "Joueurs": "3 — 6",
      "Duree": "30",
      "Ages": "14+",
      "Langues": "français",
      "Univers": "World of Darkness",
      "Gammes": "Vampire La Mascarade,Vampire The Masquerade - Vendetta",
      "Categories": "Jeu de Cartes",
      "Themes": "Horreur",
      "Mecanismes": "Bluff,Enchères,Gestion de main,Majorité,Pouvoir",
      "Editeurs": "Horrible Guild,Iello",
      "Auteurs": "Bruno Faidutti,Charlie Cleveland",
      "Illustrateurs": "Martin Mottet",
      "Date-achat": "2024-05-29",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1690443229/300/bo/40114.png"
    },
    {
      "ID": 32630,
      "Titre": "Villainous",
      "Sous-titre": "",
      "Edition": 2019,
      "Type": "basegame",
      "EAN": "4005556260676",
      "Prix": "45",
      "Joueurs": "2 — 6",
      "Duree": "40 — 120",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "Disney",
      "Gammes": "Disney Villainous,Villainous",
      "Categories": "Jeu de Cartes",
      "Themes": "Contes,Dessin animé,Fantastique,Médiéval",
      "Mecanismes": "Asymétrie,Combinaison,Gestion de main,Points d'action,Pouvoir",
      "Editeurs": "Ravensburger",
      "Auteurs": "Prospero Hall",
      "Illustrateurs": "Disney Studio",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1709937600/jpg/bg/32630.jpg"
    },
    {
      "ID": 37067,
      "Titre": "Villainous - Mauvais jusqu'à l'os",
      "Sous-titre": "",
      "Edition": 2020,
      "Type": "standalone",
      "EAN": "4005556262977",
      "Prix": "27",
      "Joueurs": "2 — 3",
      "Duree": "30 — 60",
      "Ages": "10+",
      "Langues": "français",
      "Univers": "Disney",
      "Gammes": "Disney Villainous,Villainous",
      "Categories": "Jeu de Cartes",
      "Themes": "Contes,Dessin animé,Fantastique,Médiéval",
      "Mecanismes": "Combinaison,Pouvoir",
      "Editeurs": "Ravensburger",
      "Auteurs": "Prospero Hall",
      "Illustrateurs": "Disney Studio",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1677485955/300/bl/37067.png"
    },
    {
      "ID": 8944,
      "Titre": "Wazabi",
      "Sous-titre": "",
      "Edition": 2008,
      "Type": "basegame",
      "EAN": "3421272103317,0421272103317",
      "Prix": "20",
      "Joueurs": "2 — 6",
      "Duree": "20",
      "Ages": "8+",
      "Langues": "français",
      "Univers": "",
      "Gammes": "Wazabi",
      "Categories": "Jeu de Cartes,Jeu de dés",
      "Themes": "Abstrait",
      "Mecanismes": "Défausse,Gestion de main,Jet De Dés,Pouvoir",
      "Editeurs": "Gigamic",
      "Auteurs": "Guilhem Debricon",
      "Illustrateurs": "Bravo",
      "Date-achat": "2022-01-17",
      "Proprietaire": "",
      "Cadeaux": "",
      "Emplacement": "",
      "Prix-achat": "",
      "Etat": "",
      "Prive": "non",
      "Commentaire": "",
      "Reference": "",
      "Referent": "",
      "Derniere-partie": "",
      "Cover" : "https://www.myludo.fr/img/jeux/1688478083/300/ai/8944.png"
    }
   ]

// --- PAGINATION --- 
function renderData(page = 1) {

    const container = document.querySelector('.container');
    container.innerHTML = '';

    if (!games) {
        return;
    }

    const itemsPerPage = 6;
    let numberPages = Math.ceil(games.length/itemsPerPage);

    const parentPagination = document.querySelector('.pages');
    parentPagination.innerHTML = '';

    for (let i = 1; i <= numberPages; i++) {
    const pageButton = document.createElement('button');
    pageButton.classList.add('pagination');
  pageButton.id = i
        pageButton.innerHTML = i;
        pageButton.addEventListener('click', () => changePage(i));

        parentPagination.appendChild(pageButton);

            }

    let pageIndex = page - 1;

    for (let i = (pageIndex*itemsPerPage); i < (pageIndex*itemsPerPage)+itemsPerPage; i++) {
    
    if (!games[i]) { break };

    const list = document.createElement('div');
        list.classList.add('list');
    
    const title = document.createElement('h3');
        title.classList.add('title');
        title.innerText = games[i].Titre;

    const cover = document.createElement('img');
    cover.classList.add('cover');
    cover.src = games[i].Cover;

    const category = document.createElement('p');
        category.classList.add('cat');
        category.innerHTML = `<b>Catégorie</b> : ${games[i].Categories.replace(",", ", ")}`;

    const nbPlayer = document.createElement('p');
        nbPlayer.classList.add('player');
        nbPlayer.innerHTML = `<b>Joueur.euses</b> : ${typeof games[i].Joueurs === 'string' ? games[i].Joueurs.replace(" — ", " à ") : games[i].Joueurs}`;

    const editor = document.createElement('p');
        editor.classList.add('editor');
        editor.innerHTML = `<b>Editeur</b> : ${games[i].Editeurs}`;

    const age = document.createElement('p');
        age.classList.add('age');
        age.innerHTML = `<b>Age</b> : ${games[i].Ages}`;

    const duration = document.createElement('p');
        duration.classList.add('duration')
        duration.innerHTML = `<b>Durée moyenne</b> : ${typeof games[i].Duree === 'string' ? games[i].Duree.replace(" — ", " à ") + ' min' : games[i].Duree + ' min'}`;

    const lang = document.createElement('p');
        lang.classList.add('lang');
        lang.innerHTML = `<b>Langue</b> : ${games[i].Langues}`;

    list.appendChild(cover)
    list.appendChild(title);
    list.appendChild(category);
    list.appendChild(nbPlayer);
    list.appendChild(age);
    list.appendChild(duration);
    list.appendChild(editor);
    list.appendChild(lang);
    
    container.appendChild(list);
}

// let activeButton = document.getElementsByClassName('.pagination')

// activeButton.forEach(button => {
//     button.addEventListener('click', () => {
//         button.classList.add('active')
//     })
// })


}

function changePage(page) {
    renderData(page);
    history.pushState({ page: page}, null, `?page=${page}`);

}


let queryString = window.location.search;
let urlParams = new URLSearchParams(queryString)
let pageVisible = parseInt(urlParams.get('page')) || 1;

renderData()

// --- RANDOM NAME HOME --- 

// function getRandomImg() {
//   let randomCover = games[Math.floor(Math.random() * games.length)].Cover;

//     return randomCover
// }

// // Remplace le contenu de l'attribu SRC dans la balise contenant l'ID "randomcover" en utilisant l'URL tirée au hasard dans le tableau coverImg
// function displayRandomCover() {
//     document.getElementById('randomcover').src = getRandomImg()
//     document.querySelector('.randomname').innerHTML = games[getRandomImg()].Titre

// }

// displayRandomCover()



