const whishlist = [{
   "ID": 77316,
   "Titre": "Arborea",
   "Sous-titre": "",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 3701358301340,
   "Prix": "59,9",
   "Joueurs": "1 — 5",
   "Duree": "90 — 120",
   "Ages": "14+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "Arborea",
   "Categories": "Jeu de plateau",
   "Themes": "Animaux,Fantastique,Nature,Onirique",
   "Mecanismes": "Placement d'ouvriers",
   "Editeurs": "Alley Cat Games,Pixie Games",
   "Auteurs": "Dani Garcia",
   "Illustrateurs": "Javier González Cava",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1726856109/jpg/cz/77316.jpg"
 },
 {
   "ID": 35809,
   "Titre": "Brass Birmingham",
   "Sous-titre": "",
   "Edition": 2019,
   "Type": "basegame",
   "EAN": 3770001556758,
   "Prix": "59",
   "Joueurs": "2 — 4",
   "Duree": "60 — 120",
   "Ages": "14+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "Brass",
   "Categories": "Jeu de plateau",
   "Themes": "Angleterre,Économie,Industrie,Révolution industrielle",
   "Mecanismes": "Combinaison,Connexion,Gestion de main,Livraison",
   "Editeurs": "Funforge,Roxley Games",
   "Auteurs": "Martin Wallace",
   "Illustrateurs": "Damien Mammoliti,David Forest,Lina Cossette",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1725618676/jpg/bj/35809.jpg"
 },
 {
   "ID": 71438,
   "Titre": "Captain Flip",
   "Sous-titre": "",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 5430003838006,
   "Prix": "27",
   "Joueurs": "2 — 5",
   "Duree": "20",
   "Ages": "8+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "Captain Flip",
   "Categories": "Jeu de tuiles",
   "Themes": "Maritime,Pirates",
   "Mecanismes": "Chance & Hasard,Choix multiples,Mémorisation,Pose de tuiles,Pouvoir,Prise de risque",
   "Editeurs": "PlayPunk",
   "Auteurs": "Paolo Mori,Remo Conzadori",
   "Illustrateurs": "Jonathan Aucomte",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1721400173/jpg/ct/71438.jpg"
 },
 {
   "ID": 59045,
   "Titre": "District Noir",
   "Sous-titre": "",
   "Edition": 2022,
   "Type": "basegame",
   "EAN": 3770026418000,
   "Prix": "17",
   "Joueurs": "Duo",
   "Duree": "15",
   "Ages": "10+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "District Noir",
   "Categories": "Jeu de Cartes",
   "Themes": "Années 50,Polar,Prohibition",
   "Mecanismes": "Bluff,Collection,Dans Ta Face,Duo,Majorité,Prise de risque",
   "Editeurs": "Spiral Editions",
   "Auteurs": "Nao Shimamura,Nobutake Dogen",
   "Illustrateurs": "Vincent Roché",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1721376017/jpg/ch/59045.jpg"
 },
 {
   "ID": 78353,
   "Titre": "Fantasy Realms",
   "Sous-titre": "Edition Deluxe",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 3663411312093,
   "Prix": "45",
   "Joueurs": "3 — 6",
   "Duree": "20",
   "Ages": "14+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "Fantasy Realms",
   "Categories": "Jeu de Cartes",
   "Themes": "Médiéval Fantastique",
   "Mecanismes": "Collection,Combinaison,Gestion de main",
   "Editeurs": "Don't Panic Games",
   "Auteurs": "Bruce Glassco",
   "Illustrateurs": "Anthony Cournoyer",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1725561335/jpg/da/78353.jpg"
 },
 {
   "ID": 67209,
   "Titre": "Faraway",
   "Sous-titre": "",
   "Edition": 2023,
   "Type": "basegame",
   "EAN": 3760273010386,
   "Prix": "17,9",
   "Joueurs": "2 — 6",
   "Duree": "20",
   "Ages": "10+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "Faraway",
   "Categories": "Jeu de Cartes",
   "Themes": "Saisons",
   "Mecanismes": "Collection,Gestion de main,Programmation,Stratégie",
   "Editeurs": "Catch Up Games",
   "Auteurs": "Corentin Lebrat,Johannes Goupy",
   "Illustrateurs": "Maxime Morin",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1725710375/jpg/cp/67209.jpg"
 },
 {
   "ID": 75080,
   "Titre": "Harmonies",
   "Sous-titre": "",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 3558380116684,
   "Prix": "35",
   "Joueurs": "1 — 4",
   "Duree": "30",
   "Ages": "10+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "Harmonies",
   "Categories": "Jeu de plateau",
   "Themes": "Animaux,Nature",
   "Mecanismes": "Combinaison",
   "Editeurs": "Libellud",
   "Auteurs": "Johan Benvenuto",
   "Illustrateurs": "Maëva Da Silva",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1726736995/jpg/cx/75080.jpg"
 },
 {
   "ID": 38930,
   "Titre": "Hel - The Last Saga",
   "Sous-titre": "",
   "Edition": 2021,
   "Type": "basegame",
   "EAN": null,
   "Prix": "120",
   "Joueurs": "1 — 4",
   "Duree": "60 — 120",
   "Ages": "10+",
   "Langues": "français,anglais,allemand,espagnol",
   "Univers": "",
   "Gammes": "HEL The Last Saga",
   "Categories": "Jeu de figurines",
   "Themes": "Exploration,Horreur,Médiéval,Mythologie,Vikings",
   "Mecanismes": "Exploration,Narration,Semi-coopération",
   "Editeurs": "Mythic Games",
   "Auteurs": "David Rakoto",
   "Illustrateurs": "Christophe Madura",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1692988959/300/bm/38930.png"
 },
 {
   "ID": 75792,
   "Titre": "Jekyll & Hyde vs Scotland Yard",
   "Sous-titre": "",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 3770000282979,
   "Prix": "17",
   "Joueurs": "Duo",
   "Duree": "20",
   "Ages": "10+",
   "Langues": "français",
   "Univers": "Jekyll & Hyde",
   "Gammes": "Jekyll vs Hyde",
   "Categories": "Jeu de Cartes",
   "Themes": "Littérature,Policier",
   "Mecanismes": "Campagne,Coopération,Plis,Scénario",
   "Editeurs": "Mandoo Games",
   "Auteurs": "Geon-Il,Olivier Cipière",
   "Illustrateurs": "Vincent Dutrait",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1714688766/jpg/cx/75792.jpg"
 },
 {
   "ID": 72402,
   "Titre": "Little Tavern",
   "Sous-titre": "",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 5425016926895,
   "Prix": "15",
   "Joueurs": "3 — 5",
   "Duree": "25",
   "Ages": "8+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "Little Tavern",
   "Categories": "Jeu de Cartes",
   "Themes": "Médiéval Fantastique",
   "Mecanismes": "Combinaison,Prise de risque,Stratégie",
   "Editeurs": "Repos Production",
   "Auteurs": "Maxime Rambourg,Théo Rivière",
   "Illustrateurs": "Gaël Lannurien",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1709736446/jpg/cu/72402.jpg"
 },
 {
   "ID": 75428,
   "Titre": "Littoral",
   "Sous-titre": "",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 832665000480,
   "Prix": "30",
   "Joueurs": "1 — 5",
   "Duree": "15 — 25",
   "Ages": "8+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "Littoral",
   "Categories": "Jeu de pions",
   "Themes": "Océan,Vacances",
   "Mecanismes": "Collection,Pioche,Pouvoir,Prise de risque",
   "Editeurs": "Randolph",
   "Auteurs": "Brian Burgoyne",
   "Illustrateurs": "Fanny Saulnier",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1723738201/jpg/cx/75428.jpg"
 },
 {
   "ID": 73349,
   "Titre": "Odin",
   "Sous-titre": "",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 7640139533388,
   "Prix": "11,5",
   "Joueurs": "2 — 6",
   "Duree": "15",
   "Ages": "7+",
   "Langues": "français,anglais,allemand,espagnol,italien,néerlandais",
   "Univers": "",
   "Gammes": "",
   "Categories": "Jeu de Cartes",
   "Themes": "Vikings",
   "Mecanismes": "Combinaison,Défausse,Gestion de main",
   "Editeurs": "Helvetiq",
   "Auteurs": "Gary Kim,Hope S. Hwang,Yohan Goh",
   "Illustrateurs": "Crocotame",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1720545145/jpg/cv/73349.jpg"
 },
 {
   "ID": 77135,
   "Titre": "Rebelles Princesses",
   "Sous-titre": "",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 3421277100212,
   "Prix": "15",
   "Joueurs": "3 — 6",
   "Duree": "30 — 60",
   "Ages": "8+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "",
   "Categories": "Jeu de Cartes",
   "Themes": "Humour,Médiéval",
   "Mecanismes": "Déduction,Mémorisation,Plis",
   "Editeurs": "Gigamic",
   "Auteurs": "Daniel Byrne,José Gerardo Guerrero,Kevin Peláez,Tirso Virgós",
   "Illustrateurs": "Alfredo Cáceres",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1722427974/jpg/cz/77135.jpg"
 },
 {
   "ID": 77898,
   "Titre": "Redac'Chef",
   "Sous-titre": "",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 691835204536,
   "Prix": "36",
   "Joueurs": "1 — 6",
   "Duree": "15 — 30",
   "Ages": "10+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "Redac'Chef",
   "Categories": "Jeu de tuiles",
   "Themes": "Journalisme",
   "Mecanismes": "Collection,Combinaison,Pose de tuiles,Temps réel",
   "Editeurs": "Alderac Entertainment Group,Flatout Games,Lucky Duck Games",
   "Auteurs": "Peter Mcpherson",
   "Illustrateurs": "Ian O'toole",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1725615181/jpg/cz/77898.jpg"
 },
 {
   "ID": 73433,
   "Titre": "Room 25 - Double Rush",
   "Sous-titre": "",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 3760372233730,
   "Prix": "8,9",
   "Joueurs": "Duo",
   "Duree": "15",
   "Ages": "12+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "Micro-Game Matagot,Room 25",
   "Categories": "Jeu de plateau",
   "Themes": "Évasion,Labyrinthe,Prison,Science-fiction",
   "Mecanismes": "Bluff,Déduction,Exploration,Objectif secret",
   "Editeurs": "Matagot",
   "Auteurs": "François Rouzé",
   "Illustrateurs": "Yan Moussu",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1717583035/jpg/cv/73433.jpg"
 },
 {
   "ID": 28965,
   "Titre": "Root",
   "Sous-titre": "Conflit dans les Sous-Bois",
   "Edition": 2019,
   "Type": "basegame",
   "EAN": 3760146645165,
   "Prix": "74,9",
   "Joueurs": "1 — 6",
   "Duree": "60 — 90",
   "Ages": "10+",
   "Langues": "français",
   "Univers": "Root",
   "Gammes": "Root",
   "Categories": "Jeu de Cartes,Jeu de plateau,Wargame",
   "Themes": "Animaux,Fantastique",
   "Mecanismes": "Affrontement Direct,Asymétrie,Combinaison,Conquête,Contrôle de zone,Gestion de main,Influence,Jet De Dés,Majorité,Mouvement de point à point,Pouvoir,Programmation,Solo",
   "Editeurs": "Matagot",
   "Auteurs": "Cole Wehrle",
   "Illustrateurs": "Kyle Ferrin",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1725565497/300/bc/28965.png"
 },
 {
   "ID": 74371,
   "Titre": "Solstis",
   "Sous-titre": "",
   "Edition": 2024,
   "Type": "basegame",
   "EAN": 3760268310538,
   "Prix": "15",
   "Joueurs": "Duo",
   "Duree": "15",
   "Ages": "8+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "",
   "Categories": "Jeu de tuiles",
   "Themes": "Montagne,Randonnée,Transport & voyage",
   "Mecanismes": "Choix multiples,Collection,Combinaison,Pose de tuiles,Pouvoir",
   "Editeurs": "Lumberjacks Studio",
   "Auteurs": "Bruno Cathala,Corentin Lebrat",
   "Illustrateurs": "Emmanuel Martin",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1723397587/jpg/cw/74371.jpg"
 },
 {
   "ID": 43745,
   "Titre": "The Specialists",
   "Sous-titre": "",
   "Edition": 2021,
   "Type": "basegame",
   "EAN": 3770011462063,
   "Prix": "45",
   "Joueurs": "1 — 4",
   "Duree": "60",
   "Ages": "14+",
   "Langues": "français,anglais,italien,néerlandais",
   "Univers": "",
   "Gammes": "The Specialists",
   "Categories": "Jeu de plateau",
   "Themes": "Casino,Gangs,Mafia,Voleur",
   "Mecanismes": "Conquête,Gestion de main,Jet De Dés,Planification",
   "Editeurs": "Explor8",
   "Auteurs": "Anne-Catherine Perrier,Dimitri Perrier,Marco Canetta,Stefania Niccolini",
   "Illustrateurs": "Christine Alcouffe",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1712586645/300/br/43745.png"
 },
 {
   "ID": 71923,
   "Titre": "The Vale of Eternity",
   "Sous-titre": "",
   "Edition": 2023,
   "Type": "basegame",
   "EAN": 3770000282986,
   "Prix": "30",
   "Joueurs": "2 — 4",
   "Duree": "30 — 45",
   "Ages": "10+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "The Vale Of Eternity",
   "Categories": "Jeu de Cartes",
   "Themes": "Fantastique,Mythologie",
   "Mecanismes": "Collection,Draft,Gestion de main",
   "Editeurs": "Blackrock Games,Mandoo Games",
   "Auteurs": "Eric Hong",
   "Illustrateurs": "Jiahui Eva Gao,Stefano Martinuz",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1726311008/jpg/ct/71923.jpg"
 },
 {
   "ID": 67722,
   "Titre": "Traîtres à Bord !",
   "Sous-titre": "",
   "Edition": 2023,
   "Type": "basegame",
   "EAN": 3770017333138,
   "Prix": "15,99",
   "Joueurs": "3 — 8",
   "Duree": "20",
   "Ages": "10+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "",
   "Categories": "Jeu d'Ambiance,Jeu de Cartes",
   "Themes": "Pirates",
   "Mecanismes": "Bluff,Déduction,Équipe,Objectif secret,Rôle secret,Trahison",
   "Editeurs": "Savana Games",
   "Auteurs": "Jean-Xia Chou",
   "Illustrateurs": "Laura Bazzoni",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1702383631/jpg/cp/67722.jpg"
 },
 {
   "ID": 42785,
   "Titre": "Twisted Fables",
   "Sous-titre": "",
   "Edition": 2021,
   "Type": "basegame",
   "EAN": 850368008800,
   "Prix": "48,3",
   "Joueurs": "Duo",
   "Duree": "30 — 60",
   "Ages": "14+",
   "Langues": "français,anglais",
   "Univers": "",
   "Gammes": "Twisted Fables",
   "Categories": "Jeu de Cartes,Jeu de figurines",
   "Themes": "Contes,Jeu vidéo,Science-fiction",
   "Mecanismes": "Affrontement Direct,Asymétrie,Combinaison,Deck building,Duo,Gestion de main,Pouvoir,Stratégie,Tactique",
   "Editeurs": "Diemension Games,Jellycube,Legion Distribution",
   "Auteurs": "Gang Wang,Gang Wong,Xiang Gao",
   "Illustrateurs": "Denys Tsiperko,Fajareka Setiawan,Ibrahem Swaid,Jarold Sng,Kyuyong Eom",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1710700708/300/bq/42785.png"
 },
 {
   "ID": 50802,
   "Titre": "Unmatched - Battle of Legends",
   "Sous-titre": "Volume Two",
   "Edition": 2022,
   "Type": "standalone",
   "EAN": null,
   "Prix": "0",
   "Joueurs": "2 — 4",
   "Duree": "20 — 40",
   "Ages": "9+",
   "Langues": "anglais",
   "Univers": "",
   "Gammes": "Unmatched",
   "Categories": "Jeu de Cartes,Jeu de figurines",
   "Themes": "Fantastique,Mythologie",
   "Mecanismes": "Affrontement Direct,Gestion de main,Pouvoir",
   "Editeurs": "Mondo Games,Restoration Games",
   "Auteurs": "Brian Neff,Chris Leder,Justin D. Jacobson,Kevin Rodgers,Noah Cohen,Rob Daviau",
   "Illustrateurs": "Zoë Van Dijk",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1683902661/jpg/by/50802.jpg"
 },
 {
   "ID": 44951,
   "Titre": "Unmatched - Bruce Lee",
   "Sous-titre": "",
   "Edition": 2019,
   "Type": "extension",
   "EAN": null,
   "Prix": "0",
   "Joueurs": "2 — 4",
   "Duree": "30 — 60",
   "Ages": "14+",
   "Langues": "anglais",
   "Univers": "",
   "Gammes": "Unmatched",
   "Categories": "Jeu de figurines",
   "Themes": "Arts martiaux,Film & Série",
   "Mecanismes": "Affrontement Direct,Asymétrie,Pouvoir",
   "Editeurs": "Mondo Games",
   "Auteurs": "Justin D. Jacobson,Rob Daviau",
   "Illustrateurs": "Oliver Barrett",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1703578323/jpg/bs/44951.jpg"
 },
 {
   "ID": 44121,
   "Titre": "Unmatched - Buffy the Vampire Slayer",
   "Sous-titre": "",
   "Edition": 2020,
   "Type": "standalone",
   "EAN": 850010229423,
   "Prix": "0",
   "Joueurs": "2 — 4",
   "Duree": "30 — 60",
   "Ages": "14+",
   "Langues": "anglais",
   "Univers": "Buffy",
   "Gammes": "Unmatched",
   "Categories": "Jeu de figurines",
   "Themes": "Contemporain,Fantastique,Film & Série",
   "Mecanismes": "Affrontement Direct,Asymétrie,Pouvoir",
   "Editeurs": "Mondo Games",
   "Auteurs": "Justin D. Jacobson,Rob Daviau",
   "Illustrateurs": "Heather Vaughan",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1703578395/jpg/bs/44121.jpg"
 },
 {
   "ID": 49628,
   "Titre": "Unmatched - Cobble & Fog",
   "Sous-titre": "",
   "Edition": 2021,
   "Type": "standalone",
   "EAN": 3760175518065,
   "Prix": "38",
   "Joueurs": "2 — 4",
   "Duree": "30",
   "Ages": "9+",
   "Langues": "français",
   "Univers": "",
   "Gammes": "Unmatched",
   "Categories": "Jeu de figurines",
   "Themes": "Époque Victorienne,Fantastique,Film & Série",
   "Mecanismes": "Affrontement Direct,Asymétrie,Pouvoir",
   "Editeurs": "Iello",
   "Auteurs": "Chris Leder,Justin D. Jacobson,Rob Daviau",
   "Illustrateurs": "Andrew Thompson,Ian O'toole",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1663668967/jpg/bx/49628.jpg"
 },
 {
   "ID": 49171,
   "Titre": "Unmatched - Deadpool",
   "Sous-titre": "",
   "Edition": 2021,
   "Type": "extension",
   "EAN": null,
   "Prix": "0",
   "Joueurs": "2 — 4",
   "Duree": "30 — 60",
   "Ages": "14+",
   "Langues": "anglais",
   "Univers": "Marvel",
   "Gammes": "Unmatched",
   "Categories": "Jeu de figurines",
   "Themes": "Contemporain,Fantastique,Film & Série,Super-héros",
   "Mecanismes": "Affrontement Direct,Asymétrie,Pouvoir",
   "Editeurs": "Mondo Games,Restoration Games",
   "Auteurs": "Brad Andres,Brian Neff,Justin D. Jacobson,Noah Cohen,Rob Daviau",
   "Illustrateurs": "Ian O'toole,Oliver Barrett",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1658664458/300/bx/49171.png"
 },
 {
   "ID": 47270,
   "Titre": "Unmatched - Hell's Kitchen",
   "Sous-titre": "",
   "Edition": 2021,
   "Type": "standalone",
   "EAN": 857476008272,
   "Prix": "0",
   "Joueurs": "2 — 4",
   "Duree": "30 — 60",
   "Ages": "14+",
   "Langues": "anglais",
   "Univers": "Marvel",
   "Gammes": "Unmatched",
   "Categories": "Jeu de figurines",
   "Themes": "Contemporain,Fantastique,Film & Série,Super-héros",
   "Mecanismes": "Affrontement Direct,Asymétrie,Pouvoir",
   "Editeurs": "Mondo Games,Restoration Games",
   "Auteurs": "Brad Andres,Brian Neff,Justin D. Jacobson,Noah Cohen,Rob Daviau",
   "Illustrateurs": "Ian O'toole,Oliver Barrett",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1703578135/jpg/bv/47270.jpg"
 },
 {
   "ID": 47271,
   "Titre": "Unmatched - Redemption Row",
   "Sous-titre": "",
   "Edition": 2021,
   "Type": "standalone",
   "EAN": 857476008289,
   "Prix": "0",
   "Joueurs": "2 — 4",
   "Duree": "30 — 60",
   "Ages": "14+",
   "Langues": "anglais",
   "Univers": "Marvel",
   "Gammes": "Unmatched",
   "Categories": "Jeu de figurines",
   "Themes": "Contemporain,Fantastique,Film & Série,Super-héros",
   "Mecanismes": "Affrontement Direct,Asymétrie,Pouvoir",
   "Editeurs": "Mondo Games,Restoration Games",
   "Auteurs": "Brad Andres,Brian Neff,Justin D. Jacobson,Noah Cohen,Rob Daviau,Tim Wiesch",
   "Illustrateurs": "Ian O'toole,Matt Taylor",
   "Envie": 5,
   "Cover": "https://www.myludo.fr/img/jeux/1652683124/jpg/bv/47271.jpg"
 }
]